service: ${self:custom.project}-email

frameworkVersion: "3"

plugins:
  - serverless-stack-termination-protection
  - "@stratiformdigital/serverless-s3-security-helper"
  - "@stratiformdigital/serverless-iam-helper"
  - serverless-plugin-scripts
  - serverless-esbuild
  - "@haftahave/serverless-ses-template"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iam:
    role:
      path: /delegatedadmin/developer/
      permissionsBoundary: arn:aws:iam::${aws:accountId}:policy/cms-cloud-admin/developer-boundary-policy
      statements:
        - Effect: "Allow"
          Action:
            - cognito-idp:ListUsers
          Resource: "*"
        - Effect: Allow
          Action:
            - sts:AssumeRole
          Resource: "*"
        - Effect: Allow
          Action:
            - ses:ListIdentities
            - ses:ListConfigurationSets
            - ses:SendTemplatedEmail
          Resource: "*"
        - Effect: Allow
          Action:
            - sns:Subscribe
            - sns:Publish
          Resource: "*"
        - Effect: Allow
          Action:
            - ec2:CreateNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DescribeVpcs
            - ec2:DeleteNetworkInterface
            - ec2:DescribeSubnets
            - ec2:DescribeSecurityGroups
          Resource: "*"

  stackTags:
    PROJECT: ${self:custom.project}
    SERVICE: ${self:service}

custom:
  project: ${env:PROJECT}
  emailEventTopicName: ${self:service}-${sls:stage}-email-events
  vpc: ${ssm:/aws/reference/secretsmanager/${self:custom.project}/${sls:stage}/vpc, ssm:/aws/reference/secretsmanager/${self:custom.project}/default/vpc}
  brokerString: ${ssm:/aws/reference/secretsmanager/${self:custom.project}/${sls:stage}/brokerString, ssm:/aws/reference/secretsmanager/${self:custom.project}/default/brokerString}
  serverlessTerminationProtection:
    stages: # Apply CloudFormation termination protection for these stages
      - master
      - val
      - production
  sesTemplates:
    addStage: true

params:
  master:
    topicNamespace: ""
  val:
    topicNamespace: ""
  production:
    topicNamespace: ""
  default:
    topicNamespace: --${self:custom.project}--${sls:stage}--

functions:
  processEmails:
    handler: handlers/processEmails.main
    environment:
      region: ${self:provider.region}
      stage: ${sls:stage}
      emailConfigSet: ${self:service}-${sls:stage}-configuration
      cognitoPoolId: ${param:CognitoUserPoolId}
    maximumRetryAttempts: 0
    timeout: 60
    memorySize: 1024
    vpc:
      securityGroupIds:
        - Ref: SecurityGroup
      subnetIds: >-
        ${self:custom.vpc.privateSubnets}

  processEmailEvents:
    handler: handlers/processEmailEvents.main
    events:
      - sns:
          arn: !Ref EmailEventTopic
          topicName: ${self:custom.emailEventTopicName}

resources:
  Conditions:
    isDev:
      Fn::Not:
        - Fn::Equals:
            - ${param:topicNamespace}
            - ""

  Resources:
    EmailEventTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.emailEventTopicName}
        DisplayName: Monitoring the sending of emails
        KmsMasterKeyId: !Ref KmsKeyForEmails

    KmsKeyForEmails:
      Type: AWS::KMS::Key
      Properties:
        EnableKeyRotation: "true"
        KeyPolicy:
          Version: "2012-10-17"
          Statement:
            - Sid: Allow access for Root User
              Effect: Allow
              Principal:
                AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
              Action: "kms:*"
              Resource: "*"
            - Sid: Allow access for Key User (SNS Service Principal)
              Effect: Allow
              Principal:
                Service: "sns.amazonaws.com"
              Action:
                - "kms:GenerateDataKey"
                - "kms:Decrypt"
              Resource: "*"
            - Sid: Allow CloudWatch events to use the key
              Effect: Allow
              Principal:
                Service: events.amazonaws.com
              Action:
                - "kms:Decrypt"
                - "kms:GenerateDataKey"
              Resource: "*"
            - Sid: Allow CloudWatch for CMK
              Effect: Allow
              Principal:
                Service:
                  - cloudwatch.amazonaws.com
              Action:
                - "kms:Decrypt"
                - "kms:GenerateDataKey*"
              Resource: "*"
            - Sid: Allow SES events to use the key
              Effect: Allow
              Principal:
                Service:
                  - ses.amazonaws.com
              Action:
                - "kms:Decrypt"
                - "kms:GenerateDataKey*"
              Resource: "*"

    EmailEventTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                  - ses.amazonaws.com
              Action:
                - sns:Subscribe
                - sns:Publish
              Resource: !Ref EmailEventTopic
        Topics:
          - !Ref EmailEventTopic

    EmailEventSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn: !Ref EmailEventTopic
        Endpoint: !GetAtt ProcessEmailEventsLambdaFunction.Arn
        Protocol: lambda

    EmailEventConfigurationSet:
      Type: AWS::SES::ConfigurationSet
      Properties:
        Name: "${self:service}-${sls:stage}-configuration"

    EmailEventConfigurationSetEventDestination:
      Type: AWS::SES::ConfigurationSetEventDestination
      Properties:
        ConfigurationSetName: !Ref EmailEventConfigurationSet
        EventDestination:
          Enabled: true
          Name: "${self:service}-${sls:stage}-destination"
          MatchingEventTypes:
            - "send"
            - "reject"
            - "bounce"
            - "complaint"
            - "delivery"
            - "open"
            - "click"
            - "renderingFailure"
            - "deliveryDelay"
            - "subscription"
          SnsDestination:
            TopicARN: !Ref EmailEventTopic

    SinkEmailTrigger:
      Type: AWS::Lambda::EventSourceMapping
      Properties:
        BatchSize: 1000
        Enabled: true
        FunctionName: !GetAtt ProcessEmailsLambdaFunction.Arn
        SelfManagedEventSource:
          Endpoints:
            KafkaBootstrapServers:
              Fn::Split:
                - ","
                - ${self:custom.brokerString}
        SourceAccessConfigurations:
          - Type: VPC_SUBNET
            URI: subnet:${self:custom.vpc.privateSubnets.0}
          - Type: VPC_SUBNET
            URI: subnet:${self:custom.vpc.privateSubnets.1}
          - Type: VPC_SUBNET
            URI: subnet:${self:custom.vpc.privateSubnets.2}
          - Type: VPC_SECURITY_GROUP
            URI: !Sub security_group:${SecurityGroup}
        StartingPosition: LATEST
        Topics:
          - aws.onemac.migration.cdc # We always want to sink onemacs data

    SinkEmailNamespacedTopicTrigger:
      Type: AWS::Lambda::EventSourceMapping
      Condition: isDev # We will only sink the namespaced topic if we're in a dev env
      Properties:
        BatchSize: 1000
        Enabled: true
        FunctionName: !GetAtt ProcessEmailsLambdaFunction.Arn
        SelfManagedEventSource:
          Endpoints:
            KafkaBootstrapServers:
              Fn::Split:
                - ","
                - ${self:custom.brokerString}
        SourceAccessConfigurations:
          - Type: VPC_SUBNET
            URI: subnet:${self:custom.vpc.privateSubnets.0}
          - Type: VPC_SUBNET
            URI: subnet:${self:custom.vpc.privateSubnets.1}
          - Type: VPC_SUBNET
            URI: subnet:${self:custom.vpc.privateSubnets.2}
          - Type: VPC_SECURITY_GROUP
            URI: !Sub security_group:${SecurityGroup}
        StartingPosition: LATEST
        Topics:
          - ${param:topicNamespace}aws.onemac.migration.cdc

    SecurityGroup:
      Type: AWS::EC2::SecurityGroup
      DeletionPolicy: Retain # VPC based lambda's are problematic when deleting the SG due to ENI attachmnent out of our control.
      Properties:
        GroupDescription: Security group for Sink Lambda Function.
        VpcId: ${self:custom.vpc.id}
        SecurityGroupEgress:
          - IpProtocol: tcp
            CidrIp: 0.0.0.0/0
            FromPort: 443
            ToPort: 443
          - IpProtocol: tcp
            CidrIp: 10.0.0.0/8
            FromPort: 9094
            ToPort: 9094