service: ${self:custom.project}-email

frameworkVersion: "3"

plugins:
  - serverless-stack-termination-protection
  - "@stratiformdigital/serverless-s3-security-helper"
  - "@stratiformdigital/serverless-iam-helper"
  - serverless-plugin-scripts
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iam:
    role:
      path: /delegatedadmin/developer/
      permissionsBoundary: arn:aws:iam::${aws:accountId}:policy/cms-cloud-admin/developer-boundary-policy
      statements:
        - Effect: Allow
          Action:
            - sts:AssumeRole
          Resource: "*"
        - Effect: Allow
          Action:
            - ses:ListIdentities
            - ses:ListConfigurationSets
          Resource: "*"

  stackTags:
    PROJECT: ${self:custom.project}
    SERVICE: ${self:service}

custom:
  project: ${env:PROJECT}
  serverlessTerminationProtection:
    stages: # Apply CloudFormation termination protection for these stages
      - master
      - val
      - production

functions:
  processEmails:
    handler: handlers/processEmails.main
    environment:
      region: ${self:provider.region}
    maximumRetryAttempts: 0
    timeout: 60
    memorySize: 1024
