name: setup
description: standard job setup
runs:
  using: "composite"
  steps:
    - name: Configure direnv
      uses: HatsuneMiku3939/direnv-action@v1

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: ".bun-version"
