name: setup
description: standard job setup
runs:
  using: "composite"
  steps:
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc

    - name: Configure direnv
      uses: HatsuneMiku3939/direnv-action@v1

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: ".bun-version"

    - name: Install dependencies
      shell: bash
      run: |
        echo "Using node $(node -v) (required major: $(sed -E 's/^v?([0-9]+).*/\1/' .nvmrc))"
        ./run install
