version: "2"
checks:
  method-lines:
    config:
      threshold: 1000 # defacto disable
exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - "src/services/ui/src/pages/faq/**"
