# Site settings

title: OneMAC Upgrade
description: >- # this means to ignore newlines until "baseurl:"
  Testing reports for OneMAC Upgrade
baseurl: "/macpro-mako" # the subpath of your site
url: "https://enterprise-cmcs.github.io/" # the base hostname & protocol for your site

github_url: "https://github.com/Enterprise-CMCS/macpro-mako"

# Build settings
theme: jekyll-report-dashboard
# plugins:

coverage:
  lines: 90
  functions: 85
  statements: 90
  branches: 80

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
nav_pages:
  - coverage.markdown
  - playwright-reports.markdown
  - releases.markdown

defaults:
  - scope:
      path: "playwright-reports/branches/*"
      type: "pages"
    values:
      layout: "playwright-branch"
  - scope:
      path: "_posts/releases/*"
      type: "posts"
    values:
      layout: "release-note"
