# Site settings

title: MACPRO MAKO
description: >- # this means to ignore newlines until "baseurl:"
  Testing reports for MACPRO MAKO
baseurl: "/" # the subpath of your site
url: "https://enterprise-cmcs.github.io/macpro-mako/" # the base hostname & protocol for your site

# Build settings
theme: minima
plugins:
  - jekyll-feed

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - coverage.markdown
  - playwright-reports.markdown

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "index.markdown"
    values:
      custom_css: [mako,playwright,coverage]
  -
    scope:
      path: "coverage.markdown"
    values:
      custom_css: [mako,coverage]
  -
    scope:
      path: "playwright-*.markdown"
      type: "pages"
    values:
      custom_css: [mako,playwright]
  -
    scope:
      path: "playwright-reports/branches/*"
      type: "pages"
    values:
      layout: "playwright-branch"

