services:
  alerts:
    path: src/services/alerts
  dashboard:
    path: src/services/dashboard
  ui-infra:
    path: src/services/ui-infra
  ui:
    path: src/services/ui
    dependsOn: ui-infra
    # params: # params will be added once other services are
    #   ecsFailureTopicArn: ${alerts.ECSFailureTopicArn}
    #   mskClusterArn: ${bigmac.MskClusterArn}
    #   brokerString: ${bigmac.BrokerString}
