services:
  alerts:
    path: src/services/alerts
  dashboard:
    path: src/services/dashboard
    params:
      CloudfrontDistributionId: ${ui-infra.CloudFrontDistributionId}
  data:
    path: src/services/data
  ui-infra:
    path: src/services/ui-infra
    params:
      ECSFailureTopicArn: ${alerts.ECSFailureTopicArn}
  api:
    path: src/services/api
    params:
      osDomainArn: ${data.OpenSearchDomainArn}
      osDomain: ${data.OpenSearchDomainEndpoint}
  auth:
    path: src/services/auth
    params:
      ApplicationEndpointUrl: ${ui-infra.ApplicationEndpointUrl}
      ApiName: ${api.ApiGatewayRestApiName}
  ui:
    path: src/services/ui
    params:
      CloudfrontDistributionId: ${ui-infra.CloudFrontDistributionId}
      S3BucketName: ${ui-infra.S3BucketName}
      ApplicationEndpointUrl: ${ui-infra.ApplicationEndpointUrl}
      ApiRegion: ${api.Region}
      ApiUrl: ${api.ApiGatewayRestApiUrl}
      ApiName: ${api.ApiGatewayRestApiName}
      CognitoRegion: ${auth.Region}
      CognitoIdentityPoolId: ${auth.IdentityPoolId}
      CognitoUserPoolId: ${auth.UserPoolId}
      CognitoUserPoolClientId: ${auth.UserPoolClientId}
      CognitoUserPoolClientDomain: ${auth.UserPoolClientDomain}
