services:
  networking:
    path: src/services/networking
  alerts:
    path: src/services/alerts
  uploads:
    path: src/services/uploads
  ui-infra:
    path: src/services/ui-infra
  dashboard:
    path: src/services/dashboard
    params:
      CloudfrontDistributionId: ${ui-infra.CloudFrontDistributionId}
  data:
    path: src/services/data
    params:
      ECSFailureTopicArn: ${alerts.ECSFailureTopicArn}
      LambdaSecurityGroupId: ${networking.LambdaSecurityGroupId}
  api:
    path: src/services/api
    params:
      ECSFailureTopicArn: ${alerts.ECSFailureTopicArn}
      osDomainArn: ${data.OpenSearchDomainArn}
      osDomain: ${data.OpenSearchDomainEndpoint}
      topicName: ${data.TopicName}
      attachmentsBucketName: ${uploads.AttachmentsBucketName}
      attachmentsBucketRegion: ${uploads.AttachmentsBucketRegion}
      attachmentsBucketArn: ${uploads.AttachmentsBucketArn}
      LambdaSecurityGroupId: ${networking.LambdaSecurityGroupId}
  auth:
    path: src/services/auth
    params:
      ApplicationEndpointUrl: ${ui-infra.ApplicationEndpointUrl}
      ApiName: ${api.ApiGatewayRestApiName}
      LambdaSecurityGroupId: ${networking.LambdaSecurityGroupId}
  ui:
    path: src/services/ui
    params:
      CloudfrontDistributionId: ${ui-infra.CloudFrontDistributionId}
      S3BucketName: ${ui-infra.S3BucketName}
      ApplicationEndpointUrl: ${ui-infra.ApplicationEndpointUrl}
      ApiRegion: ${api.Region}
      ApiUrl: ${api.ApiGatewayRestApiUrl}
      ApiName: ${api.ApiGatewayRestApiName}
      CognitoRegion: ${auth.Region}
      CognitoIdentityPoolId: ${auth.IdentityPoolId}
      CognitoUserPoolId: ${auth.UserPoolId}
      CognitoUserPoolClientId: ${auth.UserPoolClientId}
      CognitoUserPoolClientDomain: ${auth.UserPoolClientDomain}
  email:
    path: src/services/email
    params:
      ApplicationEndpointUrl: ${ui-infra.ApplicationEndpointUrl}
      osDomainArn: ${data.OpenSearchDomainArn}
      osDomain: ${data.OpenSearchDomainEndpoint}
      CognitoUserPoolId: ${auth.UserPoolId}
      LambdaSecurityGroupId: ${networking.LambdaSecurityGroupId}
