services:
  alerts:
    path: src/services/alerts
  dashboard:
    path: src/services/dashboard
  database:
    path: src/services/database
  seatool:
    path: src/services/seatool
  api:
    path: src/services/api
    params:
      issuesTableName: ${database.IssuesTableName}
      seatoolTableName: ${seatool.TableName}
  ui-infra:
    path: src/services/ui-infra
  auth:
    path: src/services/auth
    params:
      ApplicationEndpointUrl: ${ui-infra.ApplicationEndpointUrl}
      ApiName: ${api.ApiGatewayRestApiName}
  ui:
    path: src/services/ui
    params:
      CloudfrontDistributionId: ${ui-infra.CloudFrontDistributionId}
      S3BucketName: ${ui-infra.S3BucketName}
      ApplicationEndpointUrl: ${ui-infra.ApplicationEndpointUrl}
      ApiRegion: ${api.Region}
      ApiUrl: ${api.ApiGatewayRestApiUrl}
      ApiName: ${api.ApiGatewayRestApiName}
      CognitoRegion: ${auth.Region}
      CognitoIdentityPoolId: ${auth.IdentityPoolId}
      CognitoUserPoolId: ${auth.UserPoolId}
      CognitoUserPoolClientId: ${auth.UserPoolClientId}
      CognitoUserPoolClientDomain: ${auth.UserPoolClientDomain}
