services:
  alerts:
    path: src/services/alerts
  dashboard:
    path: src/services/dashboard
  database:
    path: src/services/database
  ui-infra:
    path: src/services/ui-infra
  ui:
    path: src/services/ui
    dependsOn: ui-infra
    params:
      CloudfrontDistributionId: ${ui-infra.CloudFrontDistributionId}
      S3BucketName: ${ui-infra.S3BucketName}
      ApplicationEndpointUrl: ${ui-infra.ApplicationEndpointUrl}
    # params: # params will be added once other services are
    #   ecsFailureTopicArn: ${alerts.ECSFailureTopicArn}
    #   mskClusterArn: ${bigmac.MskClusterArn}
    #   brokerString: ${bigmac.BrokerString}
