service: ${self:custom.project}-auth
frameworkVersion: "3"
plugins:
  - serverless-esbuild
  - serverless-stack-termination-protection
  - serverless-plugin-scripts
  - "@stratiformdigital/serverless-iam-helper"
  - "@stratiformdigital/serverless-s3-security-helper"
provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:REGION_A}
  stackTags:
    PROJECT: ${self:custom.project}
    SERVICE: ${self:service}
  iam:
    role:
      path: /delegatedadmin/developer/
      permissionsBoundary: arn:aws:iam::${aws:accountId}:policy/cms-cloud-admin/developer-boundary-policy
      statements:
        - Effect: "Allow"
          Action:
            - cognito-idp:AdminCreateUser
            - cognito-idp:AdminSetUserPassword
            - cognito-idp:AdminUpdateUserAttributes
          Resource: !GetAtt CognitoUserPool.Arn

custom:
  project: ${env:PROJECT} # This should always be set by direnv.
  accountId: !Sub "${AWS::AccountId}"
  serverlessTerminationProtection:
    stages:
      - master
      - val
      - production
  cognitoEmailAddress: ${ssm:/aws/reference/secretsmanager/${self:custom.project}/${sls:stage}/cognitoEmailAddress, ssm:/aws/reference/secretsmanager/${self:custom.project}/default/cognitoEmailAddress, ""}
  bootstrapUsers: ${ssm:/aws/reference/secretsmanager/${self:custom.project}/${sls:stage}/bootstrapUsers, param:bootstrapUsers}
  bootstrapUsersPassword: ${ssm:/aws/reference/secretsmanager/${self:custom.project}/${sls:stage}/bootstrapUsersPassword, ssm:/aws/reference/secretsmanager/${self:custom.project}/default/bootstrapUsersPassword}
  idm_info: ${ssm:/aws/reference/secretsmanager/${self:custom.project}/${sls:stage}/idmInfo, ""}
  scripts:
    hooks:
      deploy:finalize: |
        if [ "${self:custom.bootstrapUsers}" = "true" ];
        then
          aws lambda invoke --region ${self:provider.region} --function-name ${self:service}-${sls:stage}-bootstrapUsers --invocation-type RequestResponse /dev/null
        fi

params:
  val:
    bootstrapUsers: "true"
  production:
    bootstrapUsers: "false"
  default:
    bootstrapUsers: "true"

functions:
  bootstrapUsers:
    handler: handlers/createUsers.handler
    environment:
      userPoolId: !Ref CognitoUserPool
      bootstrapUsersPassword: ${self:custom.bootstrapUsersPassword}
      region: ${self:provider.region}

resources:
  Conditions:
    CreateEmailConfiguration:
      Fn::Not:
        - Fn::Equals:
            - ""
            - ${self:custom.cognitoEmailAddress}
    BackWithIDM:
      Fn::Not:
        - Fn::Equals:
            - ""
            - ${self:custom.idm_info}
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: True
        UserPoolName: ${sls:stage}-user-pool
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        EmailConfiguration:
          Fn::If:
            - CreateEmailConfiguration
            - EmailSendingAccount: DEVELOPER
              SourceArn: !Sub arn:aws:ses:${self:provider.region}:${AWS::AccountId}:identity/${self:custom.cognitoEmailAddress}
            - EmailSendingAccount: COGNITO_DEFAULT
        Schema:
          - Name: given_name
            AttributeDataType: String
            Mutable: true
            Required: true
          - Name: family_name
            AttributeDataType: String
            Mutable: true
            Required: true
          - Name: phone_number
            AttributeDataType: String
            Mutable: true
            Required: false
          - Name: state
            AttributeDataType: String
            Mutable: true
            Required: false
          - Name: cms-roles
            AttributeDataType: String
            Mutable: true
            Required: false
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${sls:stage}-user-pool-client
        UserPoolId: !Ref CognitoUserPool
        ExplicitAuthFlows:
          - ADMIN_NO_SRP_AUTH
        GenerateSecret: false # pragma: allowlist secret
        AllowedOAuthFlows:
          - code
        AllowedOAuthFlowsUserPoolClient: true
        AllowedOAuthScopes:
          - email
          - openid
          - aws.cognito.signin.user.admin # Needed to call Auth.currentUserInfo()
        CallbackURLs:
          - ${param:ApplicationEndpointUrl}
          - http://localhost:5000/
        DefaultRedirectURI: ${param:ApplicationEndpointUrl}
        LogoutURLs:
          - ${param:ApplicationEndpointUrl}
          - http://localhost:5000/
        SupportedIdentityProviders:
          - COGNITO
          - Fn::If:
              - BackWithIDM
              - !Ref UserPoolIdentityProviderIDM
              - !Ref AWS::NoValue
        AccessTokenValidity: 30
        IdTokenValidity: 30
        RefreshTokenValidity: 12
        TokenValidityUnits:
          AccessToken: minutes
          IdToken: minutes
          RefreshToken: hours
    UserPoolDomain:
      Type: AWS::Cognito::UserPoolDomain
      Properties:
        Domain:
          Fn::Join:
            - ""
            - - ${sls:stage}-login-
              - Ref: CognitoUserPoolClient
        UserPoolId:
          Ref: CognitoUserPool
    UserPoolIdentityProviderIDM:
      Condition: BackWithIDM
      Type: AWS::Cognito::UserPoolIdentityProvider
      Properties:
        AttributeMapping:
          email: email
          given_name: given_name
          family_name: family_name
          phone_number: phone_number
        IdpIdentifiers:
          - IdpIdentifier
        ProviderDetails:
          client_id: ${self:custom.idm_info.oidc_client_id}
          client_secret: ${self:custom.idm_info.oidc_client_secret}
          oidc_issuer: ${self:custom.idm_info.oidc_issuer}
          attributes_request_method: GET
          authorize_scopes: "email openid profile phone"
        ProviderName: IDM
        ProviderType: OIDC
        UserPoolId:
          Ref: CognitoUserPool
    CognitoIdentityPool:
      Type: AWS::Cognito::IdentityPool
      Properties:
        IdentityPoolName: ${sls:stage}IdentityPool
        AllowUnauthenticatedIdentities: false
        CognitoIdentityProviders:
          - ClientId: !Ref CognitoUserPoolClient
            ProviderName: !GetAtt CognitoUserPool.ProviderName
    CognitoIdentityPoolRoles:
      Type: AWS::Cognito::IdentityPoolRoleAttachment
      Properties:
        IdentityPoolId: !Ref CognitoIdentityPool
        Roles:
          authenticated: !GetAtt CognitoAuthRole.Arn
    CognitoAuthRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Federated: "cognito-identity.amazonaws.com"
              Action:
                - "sts:AssumeRoleWithWebIdentity"
              Condition:
                StringEquals:
                  "cognito-identity.amazonaws.com:aud": !Ref CognitoIdentityPool
                "ForAnyValue:StringLike":
                  "cognito-identity.amazonaws.com:amr": authenticated
        Policies:
          - PolicyName: "CognitoAuthorizedPolicy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "execute-api:Invoke"
                  Resource: !Sub arn:aws:execute-api:${self:provider.region}:${AWS::AccountId}:${param:ApiName}/*
  Outputs:
    UserPoolId:
      Value: !Ref CognitoUserPool
    UserPoolClientId:
      Value: !Ref CognitoUserPoolClient
    UserPoolClientDomain:
      Value: !Sub ${UserPoolDomain}.auth.${self:provider.region}.amazoncognito.com
    IdentityPoolId:
      Value: !Ref CognitoIdentityPool
    Region:
      Value: !Sub ${AWS::Region}
    BootstrapUsersPassword:
      Value: ${self:custom.bootstrapUsersPassword}
