// Auto-generated from OneMAC_SMART_DQ_Checklist_Complete_20260210_223158.xlsx
export type ChecklistItem = {
  checkId: string;
  priority: string;
  domain: string;
  attributeType: string;
  openSearchIndex: string;
  indices: string[];
  fieldName: string;
  dataType: string;
  checkDescription: string;
  expectedResult: string;
  status: string;
};

export const checklist: ChecklistItem[] = [
  {
    checkId: "DQ-001",
    priority: "",
    domain: "OneMAC",
    attributeType: "",
    openSearchIndex: "main",
    indices: ["main"],
    fieldName: "deleted",
    dataType: "boolean",
    checkDescription: "Identify all soft-deleted records",
    expectedResult: "All deleted=true records documented with reason",
    status: "Open",
  },
  {
    checkId: "DQ-002",
    priority: "1",
    domain: "OneMAC",
    attributeType: "OneMAC Identifiers",
    openSearchIndex: "main",
    indices: ["main"],
    fieldName: "origin",
    dataType: "string",
    checkDescription: "Records with NULL or empty Origin values",
    expectedResult: "Zero records with NULL origin OR documented exceptions?",
    status: "Open",
  },
  {
    checkId: "DQ-003",
    priority: "1",
    domain: "OneMAC",
    attributeType: "OneMAC Identifiers",
    openSearchIndex: "main",
    indices: ["main"],
    fieldName: "GSI1pk",
    dataType: "string",
    checkDescription: "Records with NULL GSI1pk values",
    expectedResult: "Document all records with NULL GSI1pk and confirm they should be hidden",
    status: "Open",
  },
  {
    checkId: "DQ-004",
    priority: "1",
    domain: "OneMAC",
    attributeType: "Record Unique Identifier ",
    openSearchIndex: "main",
    indices: ["main"],
    fieldName: "id",
    dataType: "string",
    checkDescription: "ID Format validation per authority type",
    expectedResult: "All IDs follow standard naming convention OR documented as legacy exception",
    status: "Open",
  },
  {
    checkId: "DQ-005",
    priority: "1",
    domain: "OneMAC",
    attributeType: "Data Integrity",
    openSearchIndex: "main",
    indices: ["main"],
    fieldName: "id",
    dataType: "string",
    checkDescription: "OneMAC submissions missing in SEA Tool",
    expectedResult: "Zero missing records OR documented reason (e.g., deleted, admin change)",
    status: "Open",
  },
  {
    checkId: "DQ-006",
    priority: "",
    domain: "OneMAC",
    attributeType: "Record Unique Identifier ",
    openSearchIndex: "main",
    indices: ["main"],
    fieldName: "id",
    dataType: "string",
    checkDescription: "SEA Tool submissions not found in OneMAC",
    expectedResult: "Document which legacy system records should/should not appear in OneMAC",
    status: "Open",
  },
  {
    checkId: "DQ-007",
    priority: "1",
    domain: "OneMAC",
    attributeType: "Key OneMAC Attribute - System Of Record ",
    openSearchIndex: "main",
    indices: ["main"],
    fieldName: "submissionDate",
    dataType: "timestamp",
    checkDescription: "NULL submissionDate for OneMAC-originated records",
    expectedResult: "Zero NULL values for OneMAC-originated records",
    status: "Open",
  },
  {
    checkId: "DQ-008",
    priority: "1",
    domain: "OneMAC",
    attributeType: "Key OneMAC Attribute - System Of Record ",
    openSearchIndex: "main",
    indices: ["main"],
    fieldName: "proposedDate",
    dataType: "timestamp",
    checkDescription: 'Proposed effective date = "Pending"',
    expectedResult: 'List all "Pending" records; define SMART handling rule',
    status: "Open",
  },
  {
    checkId: "DQ-009",
    priority: "1",
    domain: "OneMAC",
    attributeType: "Key OneMAC Attribute - System Of Record ",
    openSearchIndex: "main",
    indices: ["main"],
    fieldName: "proposedDate",
    dataType: "timestamp",
    checkDescription: "NULL proposedDate for Medicaid SPAs",
    expectedResult: 'Zero NULL values OR value = "Pending" with documentation',
    status: "Open",
  },
  {
    checkId: "DQ-010",
    priority: "1",
    domain: "OneMAC",
    attributeType: "Key OneMAC Attribute - System Of Record ",
    openSearchIndex: "main",
    indices: ["main"],
    fieldName: "submitterName",
    dataType: "string",
    checkDescription: "NULL submitterName for non-NOSO records",
    expectedResult: "Zero NULL values for non-NOSO submissions",
    status: "Open",
  },
  {
    checkId: "DQ-011",
    priority: "1",
    domain: "OneMAC",
    attributeType: "Key OneMAC Attribute - System Of Record ",
    openSearchIndex: "main",
    indices: ["main"],
    fieldName: "submitterEmail",
    dataType: "string",
    checkDescription: "NULL submitterEmail for non-NOSO records",
    expectedResult: "Zero NULL values for non-NOSO submissions",
    status: "Open",
  },
  {
    checkId: "DQ-012",
    priority: "1",
    domain: "OneMAC",
    attributeType: "Attachments",
    openSearchIndex: "main, changelog",
    indices: ["main", "changelog"],
    fieldName: "attachments",
    dataType: "object",
    checkDescription: "Mandatory attachments missing in S3",
    expectedResult: "Zero missing records",
    status: "Open",
  },
  {
    checkId: "DQ-012-A",
    priority: "1",
    domain: "OneMAC",
    attributeType: "Attachments",
    openSearchIndex: "main, changelog",
    indices: ["main", "changelog"],
    fieldName: "attachments",
    dataType: "object",
    checkDescription:
      "Submissions with no attachments in S3 but main index or changelog has attachments data",
    expectedResult: "Zero discrepancies ",
    status: "Open",
  },
  {
    checkId: "DQ-012-B",
    priority: "2",
    domain: "OneMAC",
    attributeType: "",
    openSearchIndex: "main, changelog",
    indices: ["main", "changelog"],
    fieldName: "attachments",
    dataType: "object",
    checkDescription:
      "Submissions with attachments in S3 but main index or changelog has NO attachments data",
    expectedResult: "Zero discrepancies ",
    status: "Open",
  },
  {
    checkId: "DQ-012-C",
    priority: "",
    domain: "OneMAC",
    attributeType: "",
    openSearchIndex: "main, changelog",
    indices: ["main", "changelog"],
    fieldName: "attachments",
    dataType: "object",
    checkDescription: "Submissions with no attachments in main but attachments in changelog",
    expectedResult: "Zero discrepancies OR documented reason",
    status: "Open",
  },
  {
    checkId: "DQ-013",
    priority: "",
    domain: "OneMAC",
    attributeType: "",
    openSearchIndex: "main",
    indices: ["main"],
    fieldName: "submissionDate",
    dataType: "timestamp",
    checkDescription: "Validate timestamp format (Unix epoch milliseconds)",
    expectedResult: "All timestamps in valid Unix epoch milliseconds range",
    status: "Open",
  },
  {
    checkId: "DQ-014",
    priority: "",
    domain: "OneMAC",
    attributeType: "",
    openSearchIndex: "main",
    indices: ["main"],
    fieldName: "statusDate",
    dataType: "timestamp",
    checkDescription: "Validate timestamp format (Unix epoch milliseconds)",
    expectedResult: "All timestamps in valid Unix epoch milliseconds range",
    status: "Open",
  },
  {
    checkId: "DQ-015",
    priority: "1",
    domain: "OneMAC",
    attributeType: "Record Unique Identifier ",
    openSearchIndex: "main",
    indices: ["main"],
    fieldName: "authority",
    dataType: "string",
    checkDescription: "Invalid authority values",
    expectedResult: "All records have valid authority value",
    status: "Open",
  },
  {
    checkId: "DQ-016",
    priority: "1",
    domain: "OneMAC",
    attributeType: "Record Unique Identifier ",
    openSearchIndex: "main",
    indices: ["main"],
    fieldName: "state",
    dataType: "string",
    checkDescription: "Invalid state codes",
    expectedResult: "All state codes valid (50 states + DC + 5 territories)",
    status: "Open",
  },
  {
    checkId: "DQ-017",
    priority: "1",
    domain: "OneMAC",
    attributeType: "Data Integrity",
    openSearchIndex: "main",
    indices: ["main"],
    fieldName: "currentStatus",
    dataType: "string",
    checkDescription: "Invalid status values",
    expectedResult: "All records have valid status value",
    status: "Open",
  },
  {
    checkId: "DQ-018",
    priority: "",
    domain: "OneMAC",
    attributeType: "",
    openSearchIndex: "main",
    indices: ["main"],
    fieldName: "submitterEmail",
    dataType: "string",
    checkDescription: "Invalid email format",
    expectedResult: "All email addresses follow valid format",
    status: "Open",
  },
  {
    checkId: "DQ-019",
    priority: "",
    domain: "OneMAC",
    attributeType: "",
    openSearchIndex: "main",
    indices: ["main"],
    fieldName: "raiReceivedDate",
    dataType: "timestamp",
    checkDescription: "RAI date discrepancies between export and UI",
    expectedResult: "All RAI dates consistent between export and UI",
    status: "Open",
  },
  {
    checkId: "DQ-020",
    priority: "1",
    domain: "OneMAC",
    attributeType: "Data Integrity",
    openSearchIndex: "main",
    indices: ["main"],
    fieldName: "formalRaiReceivedDate",
    dataType: "timestamp",
    checkDescription: "Formal RAI Response Date logical consistency",
    expectedResult: "Formal RAI response date should be >= RAI requested date and not in future",
    status: "Open",
  },
  {
    checkId: "DQ-021",
    priority: "",
    domain: "OneMAC",
    attributeType: "",
    openSearchIndex: "main",
    indices: ["main"],
    fieldName: "adminChangeType, changeMade, changeReason",
    dataType: "string",
    checkDescription: "Admin changes missing changeMade or changeReason",
    expectedResult: "All admin changes have changeMade and changeReason populated",
    status: "Open",
  },
  {
    checkId: "DQ-022",
    priority: "",
    domain: "OneMAC",
    attributeType: "",
    openSearchIndex: "main",
    indices: ["main"],
    fieldName: "adminChangeType",
    dataType: "string",
    checkDescription: "NOSO records not properly identified",
    expectedResult: "All NOSO records have NULL submitterName and submitterEmail",
    status: "Open",
  },
  {
    checkId: "DQ-023",
    priority: "",
    domain: "OneMAC",
    attributeType: "",
    openSearchIndex: "main",
    indices: ["main"],
    fieldName: "origin, GSI1pk",
    dataType: "string",
    checkDescription: "Identify all legacy system records (WMS/MMDL, MACPro)",
    expectedResult: "Document all legacy system sources and record counts",
    status: "Open",
  },
  {
    checkId: "DQ-024",
    priority: "",
    domain: "OneMAC",
    attributeType: "",
    openSearchIndex: "changelog",
    indices: ["changelog"],
    fieldName: "timestamp",
    dataType: "timestamp",
    checkDescription: "Validate changelog timestamp format",
    expectedResult: "All timestamps in valid Unix epoch milliseconds range",
    status: "Open",
  },
  {
    checkId: "DQ-025",
    priority: "",
    domain: "OneMAC",
    attributeType: "",
    openSearchIndex: "changelog",
    indices: ["changelog"],
    fieldName: "origin",
    dataType: "string",
    checkDescription: "NULL or invalid origin in changelog",
    expectedResult: "All changelog events have valid origin",
    status: "Open",
  },
  {
    checkId: "DQ-026",
    priority: "",
    domain: "OneMAC",
    attributeType: "",
    openSearchIndex: "changelog",
    indices: ["changelog"],
    fieldName: "isAdminChange",
    dataType: "boolean",
    checkDescription: "Admin changes in changelog missing isAdminChange flag",
    expectedResult: "All records with changeMade/changeReason have isAdminChange=true",
    status: "Open",
  },
  {
    checkId: "DQ-027",
    priority: "",
    domain: "OneMAC",
    attributeType: "",
    openSearchIndex: "changelog",
    indices: ["changelog"],
    fieldName: "changeMade",
    dataType: "string",
    checkDescription: "Verify changeMade populated for admin changes",
    expectedResult: "All admin changes have changeMade value",
    status: "Open",
  },
  {
    checkId: "DQ-028",
    priority: "",
    domain: "OneMAC",
    attributeType: "",
    openSearchIndex: "changelog",
    indices: ["changelog"],
    fieldName: "changeReason",
    dataType: "string",
    checkDescription: "Verify changeReason populated for admin changes",
    expectedResult: "All admin changes have changeReason value",
    status: "Open",
  },
  {
    checkId: "DQ-029",
    priority: "",
    domain: "OneMAC",
    attributeType: "",
    openSearchIndex: "users",
    indices: ["users"],
    fieldName: "states",
    dataType: "array",
    checkDescription: "Validate state access list for state users",
    expectedResult: "All state users have at least one state assigned",
    status: "Open",
  },
  {
    checkId: "DQ-030",
    priority: "",
    domain: "OneMAC",
    attributeType: "",
    openSearchIndex: "roles",
    indices: ["roles"],
    fieldName: "id",
    dataType: "string",
    checkDescription: "Validate role ID format",
    expectedResult: "All role IDs follow standard format",
    status: "Open",
  },
  {
    checkId: "DQ-031",
    priority: "",
    domain: "OneMAC",
    attributeType: "",
    openSearchIndex: "roles",
    indices: ["roles"],
    fieldName: "email",
    dataType: "string",
    checkDescription: "Validate email format in roles",
    expectedResult: "All email addresses follow valid format",
    status: "Open",
  },
  {
    checkId: "DQ-032",
    priority: "",
    domain: "OneMAC",
    attributeType: "",
    openSearchIndex: "roles",
    indices: ["roles"],
    fieldName: "lastModifiedDate",
    dataType: "timestamp",
    checkDescription: "Validate role modification timestamp",
    expectedResult: "All timestamps in valid Unix epoch milliseconds range",
    status: "Open",
  },
] as const;
