service: ${self:custom.project}-api
frameworkVersion: "3"
package:
  individually: true
plugins:
  - serverless-bundle
  - serverless-stack-termination-protection
  - "@stratiformdigital/serverless-iam-helper"
  - "@stratiformdigital/serverless-s3-security-helper"
  - serverless-plugin-scripts
provider:
  name: aws
  runtime: nodejs18.x
  environment:
    issuesTable: ${param:issuesTableName}
  logs:
    restApi: true
  region: ${env:REGION_A}
  stackTags:
    PROJECT: ${self:custom.project}
    SERVICE: ${self:service}
  iam:
    role:
      path: /delegatedadmin/developer/
      permissionsBoundary: arn:aws:iam::${aws:accountId}:policy/cms-cloud-admin/developer-boundary-policy
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:DescribeTable
            - dynamodb:Get*
            - dynamodb:BatchWrite*
            - dynamodb:BatchGet*
          Resource: "*"

custom:
  project: ${env:PROJECT}
  accountId: !Sub "${AWS::AccountId}"
  stage: ${opt:stage, self:provider.stage}
  serverlessTerminationProtection:
    stages: # Apply CloudFormation termination protection for these stages
      - master
      - val
      - production
  scripts:
    commands:
      seturl: |
        set -e
        api_url=$(aws cloudformation describe-stacks --stack-name om-api-play --query 'Stacks[0].Outputs[?OutputKey==`ApiGatewayRestApiUrl`].OutputValue' --output text)
        echo $api_url
        export API_URL=$api_url

        
functions:
  getIssues:
    handler: handlers/getIssues.handler
    maximumRetryAttempts: 0
    environment:
      tableName: ${param:issuesTableName}
      region: ${self:provider.region}
    events:
      - http:
          path: /issues
          method: get
          cors: true
  getIssue:
    handler: handlers/getIssue.handler
    maximumRetryAttempts: 0
    environment:
      tableName: ${param:issuesTableName}
      region: ${self:provider.region}
    events:
      - http:
          path: /issues/{id}
          method: get
          cors: true
  createIssue:
    handler: handlers/createIssue.handler
    maximumRetryAttempts: 0
    environment:
      tableName: ${param:issuesTableName}
      region: ${self:provider.region}
    events:
      - http:
          path: /issues
          method: post
          cors: true
  deleteIssue:
    handler: handlers/deleteIssue.handler
    maximumRetryAttempts: 0
    environment:
      tableName: ${param:issuesTableName}
      region: ${self:provider.region}
    events:
      - http:
          path: /issues/{id}
          method: delete
          cors: true
  updateIssue:
    handler: handlers/updateIssue.handler
    maximumRetryAttempts: 0
    environment:
      tableName: ${param:issuesTableName}
      region: ${self:provider.region}
    events:
      - http:
          path: /issues/{id}
          method: put
          cors: true
resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId: !Ref ApiGatewayRestApi
    GatewayResponseDefault5XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId: !Ref ApiGatewayRestApi
  Outputs:
    ApiGatewayRestApiName:
      Value: !Ref ApiGatewayRestApi
    ApiGatewayRestApiUrl:
      Value: !Sub https://${ApiGatewayRestApi}.execute-api.${self:provider.region}.amazonaws.com/${self:custom.stage}
    Region:
      Value: !Sub ${AWS::Region}
