export const STATE_CODES = [
  "AL",
  "AK",
  "AS",
  "AZ",
  "AR",
  "CA",
  "CO",
  "CT",
  "DE",
  "DC",
  "FM",
  "FL",
  "GA",
  "GU",
  "HI",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MH",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "MP",
  "OH",
  "OK",
  "OR",
  "PW",
  "PA",
  "PR",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VT",
  "VI",
  "VA",
  "WA",
  "WV",
  "WI",
  "WY",
  "ZZ",
] as const;
export type StateCode = (typeof STATE_CODES)[number];

export const FULL_STATES = [
  { label: "Alabama", value: "AL", code: "01" },
  { label: "Alaska", value: "AK", code: "02" },
  { label: "American Samoa", value: "AS", code: "00" },
  { label: "Arizona", value: "AZ", code: "04" },
  { label: "Arkansas", value: "AR", code: "05" },
  { label: "California", value: "CA", code: "06" },
  { label: "Colorado", value: "CO", code: "08" },
  { label: "Connecticut", value: "CT", code: "09" },
  { label: "Delaware", value: "DE", code: "10" },
  { label: "District of Columbia", value: "DC", code: "11" },
  { label: "Florida", value: "FL", code: "12" },
  { label: "Georgia", value: "GA", code: "13" },
  { label: "Guam", value: "GU", code: "00" },
  { label: "Hawaii", value: "HI", code: "15" },
  { label: "Idaho", value: "ID", code: "16" },
  { label: "Illinois", value: "IL", code: "17" },
  { label: "Indiana", value: "IN", code: "18" },
  { label: "Iowa", value: "IA", code: "19" },
  { label: "Kansas", value: "KS", code: "20" },
  { label: "Kentucky", value: "KY", code: "21" },
  { label: "Louisiana", value: "LA", code: "22" },
  { label: "Maine", value: "ME", code: "23" },
  { label: "Maryland", value: "MD", code: "24" },
  { label: "Massachusetts", value: "MA", code: "25" },
  { label: "Michigan", value: "MI", code: "26" },
  { label: "Minnesota", value: "MN", code: "27" },
  { label: "Mississippi", value: "MS", code: "28" },
  { label: "Missouri", value: "MO", code: "29" },
  { label: "Montana", value: "MT", code: "30" },
  { label: "Nebraska", value: "NE", code: "31" },
  { label: "Nevada", value: "NV", code: "32" },
  { label: "New Hampshire", value: "NH", code: "33" },
  { label: "New Jersey", value: "NJ", code: "34" },
  { label: "New Mexico", value: "NM", code: "35" },
  { label: "New York", value: "NY", code: "36" },
  { label: "North Carolina", value: "NC", code: "37" },
  { label: "North Dakota", value: "ND", code: "38" },
  { label: "Northern Mariana Islands", value: "MP", code: "00" },
  { label: "Ohio", value: "OH", code: "39" },
  { label: "Oklahoma", value: "OK", code: "40" },
  { label: "Oregon", value: "OR", code: "41" },
  { label: "Pennsylvania", value: "PA", code: "42" },
  { label: "Puerto Rico", value: "PR", code: "72" },
  { label: "Rhode Island", value: "RI", code: "44" },
  { label: "South Carolina", value: "SC", code: "45" },
  { label: "South Dakota", value: "SD", code: "46" },
  { label: "Tennessee", value: "TN", code: "47" },
  { label: "Texas", value: "TX", code: "48" },
  { label: "Utah", value: "UT", code: "49" },
  { label: "Vermont", value: "VT", code: "50" },
  { label: "Virgin Islands", value: "VI", code: "00" },
  { label: "Virginia", value: "VA", code: "51" },
  { label: "Washington", value: "WA", code: "53" },
  { label: "West Virginia", value: "WV", code: "54" },
  { label: "Wisconsin", value: "WI", code: "55" },
  { label: "Wyoming", value: "WY", code: "56" },
];
