# Refer to this service's README to configure all required SSM parameters.
service: ${self:custom.project}-ui-infra

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stackTags:
    PROJECT: ${self:custom.project}
    SERVICE: ${self:service}
  iam:
    role:
      path: /delegatedadmin/developer/
      permissionsBoundary: arn:aws:iam::${aws:accountId}:policy/cms-cloud-admin/developer-boundary-policy

plugins:
  - serverless-plugin-scripts
  - serverless-stack-termination-protection
  - "@stratiformdigital/serverless-iam-helper"
  - "@stratiformdigital/serverless-s3-security-helper"
  - "@enterprise-cmcs/serverless-waf-plugin"

custom:
  project: ${env:PROJECT}
  region: ${opt:region, self:provider.region}
  serverlessTerminationProtection:
    stages:
      - master
      - val
      - production
  stage: ${sls:stage} # This is junk.. required by the serverless-waf-plugin.  Due for refactor
  cloudfrontCertificateArn: ${ssm:/aws/reference/secretsmanager/${self:custom.project}/${sls:stage}/cloudfront/certificateArn, ssm:/aws/reference/secretsmanager/${self:custom.project}/default/cloudfront/certificateArn, ""}
  cloudfrontDomainName: ${ssm:/aws/reference/secretsmanager/${self:custom.project}/${sls:stage}/cloudfront/domainName, ""}
  webAclName: ${sls:stage}-${self:service}-webacl
  wafExcludeRules:
    wafScope: CLOUDFRONT
  firehoseStreamName: aws-waf-logs-${self:service}-${sls:stage}-firehose
  s3SecurityHelper:
    skipPolicyCreation:
      - S3Bucket
      - LoggingBucket
  scripts:
    hooks:
      # Associate the WAF ACL with the Firehose Delivery Stream
      deploy:finalize: |
        wafAclArn=`aws wafv2 list-web-acls --scope CLOUDFRONT | jq -r '.WebACLs | .[] | select(.Name=="${self:custom.webAclName}") | .ARN'`
        firehoseStreamArn=`aws firehose describe-delivery-stream --delivery-stream-name ${self:custom.firehoseStreamName} | jq -r '.DeliveryStreamDescription.DeliveryStreamARN'`
        aws wafv2 put-logging-configuration \
          --logging-configuration ResourceArn=$wafAclArn,LogDestinationConfigs=$firehoseStreamArn \
          --region ${self:provider.region}

resources:
  Conditions:
    CreateCustomCloudFrontDomain:
      Fn::And:
        - Fn::Not:
            - Fn::Equals:
                - ""
                - ${self:custom.cloudfrontCertificateArn}
        - Fn::Not:
            - Fn::Equals:
                - ""
                - ${self:custom.cloudfrontDomainName}
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
      DeletionPolicy: Delete
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: "s3:GetObject"
              Resource: !Sub arn:aws:s3:::${S3Bucket}/*
              Principal:
                CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
            - Effect: Deny
              Principal: "*"
              Action: "*"
              Resource:
                - !Sub "${S3Bucket.Arn}"
                - !Sub "${S3Bucket.Arn}/*"
              Condition:
                Bool:
                  "aws:SecureTransport": false
        Bucket: !Ref S3Bucket
    LoggingBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: !Sub ${self:service}-${sls:stage}-cloudfront-logs-${AWS::AccountId}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: "AES256"
        AccessControl: LogDeliveryWrite
        OwnershipControls:
          Rules:
            - ObjectOwnership: BucketOwnerPreferred
      DeletionPolicy: Delete
    LoggingBucketPolicy:
      Type: "AWS::S3::BucketPolicy"
      Properties:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: "s3:PutObject"
              Resource: !Sub arn:aws:s3:::${LoggingBucket}/*
              Principal:
                AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            - Effect: Deny
              Principal: "*"
              Action: "*"
              Resource:
                - !Sub "${LoggingBucket.Arn}"
                - !Sub "${LoggingBucket.Arn}/*"
              Condition:
                Bool:
                  "aws:SecureTransport": false
        Bucket: !Ref LoggingBucket
    CloudFrontOriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: OAI to prevent direct public access to the bucket
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Comment: CloudFront Distro for the static website hosted in S3
          Aliases:
            Fn::If:
              - CreateCustomCloudFrontDomain
              - - ${self:custom.cloudfrontDomainName}
              - !Ref AWS::NoValue
          Origins:
            - DomainName: !GetAtt S3Bucket.DomainName
              Id: S3Origin
              S3OriginConfig:
                OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
          Enabled: true
          HttpVersion: "http2"
          DefaultRootObject: index.html
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
            Compress: true
            TargetOriginId: S3Origin
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: none
            ViewerProtocolPolicy: redirect-to-https
            FunctionAssociations:
              - EventType: viewer-response
                FunctionARN: !GetAtt HstsCloudfrontFunction.FunctionMetadata.FunctionARN
          ViewerCertificate:
            Fn::If:
              - CreateCustomCloudFrontDomain
              - AcmCertificateArn: ${self:custom.cloudfrontCertificateArn}
                MinimumProtocolVersion: TLSv1.2_2021
                SslSupportMethod: sni-only
              - CloudFrontDefaultCertificate: true
          CustomErrorResponses:
            - ErrorCode: 403
              ResponseCode: 403
              ResponsePagePath: /index.html
          WebACLId: !GetAtt WafPluginAcl.Arn
          Logging:
            Bucket: !Sub "${LoggingBucket}.s3.amazonaws.com"
            Prefix: AWSLogs/CLOUDFRONT/${sls:stage}/
    CloudFrontLogs400ErrorCount:
      Type: AWS::Logs::MetricFilter
      Properties:
        FilterName: CloudFront400ErrorCount
        FilterPattern: '"HTTP/1.0" 4**'
        MetricTransformations:
          - MetricValue: "1"
            DefaultValue: "0"
            MetricNamespace: "${self:service}-${sls:stage}/CloudFront/ERRORS"
            MetricName: "CloudFront400ErrorCount"
            Unit: Count
        DistributionId: !Ref CloudFrontDistribution
    CloudFrontLogs400ErrorCountAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        DatapointsToAlarm: 1
        AlarmActions:
          - ${param:ECSFailureTopicArn}
        AlarmName: "mako-${sls:stage}-cloudfront-400-errors"
        ComparisonOperator: GreaterThanOrEqualToThreshold
        EvaluationPeriods: 2
        Period: 300
        Threshold: 1
        MetricName: CloudFront400ErrorCount
        Namespace: "${self:service}-${sls:stage}/CloudFront/ERRORS"
        Statistic: Sum

    CloudFrontLogs500ErrorCount:
      Type: AWS::Logs::MetricFilter
      Properties:
        FilterName: CloudFront500ErrorCount
        FilterPattern: '"HTTP/1.0" 5**'
        MetricTransformations:
          - MetricValue: "1"
            DefaultValue: "0"
            MetricNamespace: "${self:service}-${sls:stage}/CloudFront/ERRORS"
            MetricName: "CloudFront500ErrorCount"
            Unit: Count
        DistributionId: !Ref CloudFrontDistribution

    CloudFrontLogs500ErrorCountAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        DatapointsToAlarm: 1
        AlarmActions:
          - ${param:ECSFailureTopicArn}
        AlarmName: "mako-${sls:stage}-cloudfront-500-errors"
        ComparisonOperator: GreaterThanOrEqualToThreshold
        EvaluationPeriods: 2
        Period: 300
        Threshold: 1
        MetricName: CloudFront500ErrorCount
        Namespace: "${self:service}-${sls:stage}/CloudFront/ERRORS"
        Statistic: Sum

    HstsCloudfrontFunction:
      Type: AWS::CloudFront::Function
      Properties:
        AutoPublish: true
        FunctionCode: |
          function handler(event) {
            var response = event.response;
            var headers = response.headers;
            headers['strict-transport-security'] = { value: 'max-age=63072000; includeSubdomains; preload'};
            return response;
          }
        FunctionConfig:
          Comment: This function adds headers to implement HSTS
          Runtime: cloudfront-js-1.0
        Name: hsts-${self:custom.project}-${sls:stage}
    ###############This code block enables logging on waf and sends all logs to s3.##################################
    WaflogsUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub ${AWS::AccountId}-${self:service}-${sls:stage}-waflogs
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
    Firehose:
      Type: AWS::KinesisFirehose::DeliveryStream
      Properties:
        DeliveryStreamName: ${self:custom.firehoseStreamName}
        ExtendedS3DestinationConfiguration:
          RoleARN: !GetAtt DeliveryRole.Arn
          BucketARN: !GetAtt WaflogsUploadBucket.Arn
          Prefix: AWSLogs/WAF/${sls:stage}/
          BufferingHints:
            IntervalInSeconds: 300
            SizeInMBs: 5
          CompressionFormat: UNCOMPRESSED
    DeliveryRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: ""
              Effect: Allow
              Principal:
                Service: firehose.amazonaws.com
              Action: "sts:AssumeRole"
              Condition:
                StringEquals:
                  "sts:ExternalId": !Ref "AWS::AccountId"
    DeliveryPolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: "firehose_delivery_policy"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "s3:AbortMultipartUpload"
                - "s3:GetBucketLocation"
                - "s3:GetObject"
                - "s3:ListBucket"
                - "s3:ListBucketMultipartUploads"
                - "s3:PutObject"
              Resource:
                - !Sub ${WaflogsUploadBucket.Arn}/*
                - !Sub ${WaflogsUploadBucket.Arn}/*
        Roles:
          - !Ref DeliveryRole
    ApplicationEndpointUrl:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /${self:custom.stage}/${self:service}/application_endpoint
        Type: String
        Value:
          Fn::If:
            - CreateCustomCloudFrontDomain
            - https://${self:custom.cloudfrontDomainName, ""}/
            - Fn::Join:
                - ""
                - - https://
                  - Fn::GetAtt:
                      - CloudFrontDistribution
                      - DomainName
                  - "/"
  Outputs:
    S3BucketName:
      Value: !Ref S3Bucket
    CloudFrontDistributionId:
      Value: !Ref CloudFrontDistribution
    CloudFrontEndpointUrl:
      Value: !Sub https://${CloudFrontDistribution.DomainName}
    ApplicationEndpointUrl:
      Value: !GetAtt ApplicationEndpointUrl.Value
