// seatool types/typeids organized by authority id
export const SEATOOL_TYPES: {
  [key: string]: {
    [key: string]: string;
  };
} = {
  "122": {
    "4": "1915(b) Waivers Do Not Use",
    "31": "Hlth Care Ref (HCR) Do Not Use",
    "32": "MSTAT Do Not Use",
    "111": "1915 (b) Waiver",
  },
  "123": {
    "5": "1915(c) Waivers Do Not Use",
    "33": "Hlth Care Ref (HCR) Do Not Use",
    "34": "MSTAT Do Not Use",
    "112": "App K-Emergency Response",
    "113": "Aged/Disabled",
    "114": "Intellectual Disability/Developmental Disability",
    "115": "Mental Illness",
  },
  "124": {
    "40": "Program Changes",
    "41": "Eligibility",
    "42": "Application/Enroll",
    "43": "Coverage",
    "44": "Cost Sharing",
    "45": "Delivery System",
    "46": "Payment Methodology",
    "47": "Funding",
    "48": "Hlth Srvc Initiative",
    "49": "Other",
    "61": "MAGI - CHIP SPA",
    "64": "Affordable Care Act",
    "68": "MAGI - CHIP SPA",
    "116": "Disaster Relief",
  },
  "125": {
    "1": "Institutional Do Not Use",
    "2": "Non-Institut (NIPT) Do Not Use",
    "3": "Pharmacy Payment Do Not Use",
    "6": "1915(i) SPAs Do Not Use",
    "7": "1915(j) Waivers Do Not Use",
    "8": "1915(k) Waivers Do Not Use",
    "9": "1932(a) Managed Care Do Not Use",
    "10": "1937 Benchmark Do Not Use",
    "11": "ACA Contracts Do Not Use",
    "12": "Contracts Do Not Use",
    "13": "Coverage Do Not Use",
    "14": "Disease Management Do Not Use",
    "15": "DSG Do Not Use",
    "16": "Eligibility Do Not Use",
    "17": "EPSDT Do Not Use",
    "18": "Hlth Care Ref (HCR) Do Not Use",
    "19": "MSTAT Do Not Use",
    "20": "Institutional Payment (NIRT) Do Not Use",
    "21": "Non - HCR SPAs Do Not Use",
    "22": "Pharmacy Coverage Do Not Use",
    "23": "RAC SPAs Do Not Use",
    "24": "Rehab (REH) Do Not Use",
    "25": "School Based Service Do Not Use",
    "26": "SPA Compliance Lttr Do Not Use",
    "27": "SPA Companion Lttr Do Not Use",
    "28": "TCM Do Not Use",
    "29": "ThirdParty Liability Do Not Use",
    "30": "Tribal Consultation Do Not Use",
    "35": "PACE Do Not Use",
    "37": "Health Homes Do Not Use",
    "38": "Cost Sharing Do Not Use",
    "50": "Administrative Do Not Use",
    "51": "Provider Scrn/Enroll Do Not Use",
    "52": "Section 6032 Do Not Use",
    "53": "Vaccines Do Not Use",
    "54": "CoPayments Do Not Use",
    "55": "Single State Agency Do Not Use",
    "56": "NEMT Do Not Use",
    "57": "Cost Effectiveness Do Not Use",
    "58": "Reimbursement Do Not Use",
    "59": "Policy Do Not Use",
    "60": "MAGI - Medicaid SPA Do Not Use",
    "62": "Affordable Care Act Do Not Use",
    "67": "FMAP Do Not Use",
    "69": "ABP Do Not Use",
    "73": "Non-Institutional Payment (NIPT) Do Not Use",
    "82": "Recovery Audit Contractor",
    "83": "Disaster Relief",
    "84": "Administrative",
    "85": "Estate Recovery",
    "86": "Reimbursement – Non-Institutional",
    "87": "Reimbursement –Institutional",
    "88": "Reimbursement – FMAP",
    "89": "Reimbursement – UPL",
    "90": "Reimbursement – Adm",
    "91": "Coverage – Non-Institutional 1905(a) Services",
    "92": "Coverage – Institutional 1905(a) Services",
    "93": "1915(i) – State Plan HCBS",
    "94": "1915(j) – Self Directed Personal Assistance Services",
    "95": "1915(k) – Community First Choice",
    "96": "1915(l) – Support Act IMD Coverage",
    "97": "Alternative Benefit Plans",
    "98": "PACE",
    "99": "Health Homes",
    "100": "Coverage – Other Services",
    "101": "Pharmacy – Payment",
    "102": "Pharmacy – Coverage",
    "103": "Pharmacy DUR",
    "104": "1932(a) Managed Care",
    "105": "Third Party Liability",
    "106": "Cost Sharing & Premiums",
    "107": "Eligibility",
    "108": "Premium Assistance",
    "109": "Tribal Consultation",
    "110": "Program Integrity",
    "117": "Administration",
  },
  "128": { "70": "Contract", "71": "RFP/SOW", "72": "E&E APD" },
  "129": { "79": "PA CAP", "80": "MAC Plan", "81": "SW CAP" },
  "130": { "77": "Institutional Payment (NIRT)", "78": "Non-Institut (NIPT)" },
};
