// seatool subtypes/subtypeids organized by authority and type id
export const SEATOOL_SUB_TYPES: {
  [key: string]: {
    [key: string]: {
      [key: string]: string;
    };
  };
} = {
  "121": { "116": { "1004": "Test Type" } },
  "122": {
    "4": {
      "21": "1915 (b) (1) Do Not Use",
      "22": "1915 (b) (2) Do Not Use",
      "23": "1915 (b) (3) Do Not Use",
      "24": "1915 (b) (4) Do Not Use",
      "270": "\"Multiple - see \"\"Remarks\"\" memo Do Not Use\"",
      "375": "Dual Eligibles Do Not Use",
    },
    "31": {
      "143": "1915(i) HCBS Do Not Use",
      "144": "1915(i)-2402(d) ACA Do Not Use",
    },
    "111": {
      "820": "1915 (b) (1)",
      "821": "1915 (b) (2)",
      "822": "1915 (b) (3)",
      "823": "1915 (b) (4)",
      "825": "Dual Eligibles",
      "992": "Concurrent 1915(c)",
      "993": "Concurrent 1915(i)",
      "994": "Concurrent 1915(j)",
      "995": "Concurrent 1915(k)",
      "996": "Concurrent 1115",
      "997": "ARP 9817",
      "998": "PHE Related",
    },
  },
  "123": {
    "5": {
      "25": "Aged & Disabled Do Not Use",
      "26": "Autism Do Not Use",
      "27": "Development Disability Do Not Use",
      "28": "HIV/AIDS Do Not Use",
      "29": "Hospice Do Not Use",
      "30": "Intellectual Disability Do Not Use",
      "31": "Medically Fragile Do Not Use",
      "32": "Other Do Not Use",
      "33": "Severe Emotional Disturb Do Not Use",
      "34": "Technology Dependent Do Not Use",
      "35": "Traum Brain Injury (TBI) Do Not Use",
      "273": "Physical Disability Do Not Use",
      "274": "Phys/Other Disabilities Do Not Use",
      "275": "ID/DD/Autism Do Not Use",
      "276": "ID/DD Do Not Use",
      "277": "Aged Do Not Use",
      "278": "Medically/Fragile/TechDepend Do Not Use",
      "279": "Mental Illness Do Not Use",
      "281": "MI/SED Do Not Use",
      "282": "BI/TechDepend Do Not Use",
      "287": "Acquired Brain Injury (ABI) Do Not Use",
      "358": "Innnovations Do Not Use",
    },
    "33": {
      "267": "1915(i) HCBS Do Not Use",
      "268": "1915(i)-2402(d) ACA Do Not Use",
    },
    "34": { "269": "Other Do Not Use" },
    "112": {
      "827": "COVID",
      "828": "Flood",
      "829": "Hurricane",
      "830": "Other",
      "831": "Tropical Storms",
      "832": "Pandemic/Epidemic",
      "833": "Wild Fire",
      "846": "ARP 9817",
    },
    "113": {
      "834": "Aged (age 65 and older)",
      "835": "Disabled (physical)",
      "836": "Disabled (other)",
      "837": "Brain injury",
      "838": "HIV/AIDS",
      "839": "Medically Fragile",
      "840": "Technology Dependent",
      "847": "ARP 9817",
      "848": "PHE Related",
      "980": "Concurrent 1915(b)",
      "981": "Concurrent 1932(a)",
      "982": "Concurrent 1115",
      "983": "Concurrent 1915(j)",
    },
    "114": {
      "841": "Autism",
      "842": "Developmental Disability",
      "843": "Intellectual Disability",
      "849": "ARP 9817",
      "850": "PHE Related",
      "984": "Concurrent 1932(a)",
      "985": "Concurrent 1115",
      "986": "Concurrent 1915(b)",
      "987": "Concurrent 1915(j)",
    },
    "115": {
      "844": "Serious Emotional Disturbance",
      "845": "Mental Illness",
      "851": "ARP 9817",
      "852": "PHE Related",
      "988": "Concurrent 1932(a)",
      "989": "Concurrent 1115",
      "990": "Concurrent 1915(b)",
      "991": "Concurrent 1915(j)",
    },
  },
  "124": {
    "40": {
      "289": "Separate",
      "290": "Medicaid Expansion",
      "291": "Combination",
    },
    "41": {
      "292": "FPL",
      "293": "Pregnant Women",
      "294": "State Employee Children",
      "295": "Prenatal Services (Unborn)",
      "296": "Lawfully Residing: 214 Option",
      "297": "Cap/Freeze Enrollment",
      "298": "MAGI Converation",
      "299": "Childn Losing Medicaid 2101(f)",
      "300": "Other Eligibility Requirement",
      "887": "Extended Postpartum",
    },
    "42": {
      "301": "Application Process",
      "302": "Continuous Eligibility",
      "303": "Presumptive Eligibility",
      "304": "Express Lane",
      "305": "Deemed Newborns",
      "306": "Waiting Period",
      "307": "Premium Grace Period",
      "308": "Premium Lock-Out Period",
      "309": "Citizenship Documentation",
      "310": "SSNs",
      "311": "ACA-Application Type",
      "312": "ACA-Coordination",
      "313": "Other:App/Enroll",
    },
    "43": {
      "314": "Add Benefits",
      "315": "Delete Benefits",
      "316": "Change Benefit Limit",
      "317": "Hospice: Concurrent Care",
      "318": "Mental Health Parity",
      "319": "CHIPRA Dental",
      "320": "Benchmark",
      "321": "Secretary Approved",
      "322": "Supplemental Dentall",
      "323": "Other Benefit Change",
    },
    "44": {
      "324": "Copayments",
      "325": "Premiums",
      "326": "Enrollment Fee",
      "327": "Deductibles",
      "328": "5% Limit",
      "329": "Other Cost-Sharing",
    },
    "45": {
      "332": "Managed Care",
      "333": "Fee for Service",
      "334": "Premium Assistance",
      "335": "Other Delivery System",
    },
    "46": { "330": "PPS: FQHC/RHC", "331": "Other Payment" },
    "49": {
      "336": "Public Notice",
      "337": "PERM",
      "338": "Tribal Consultation",
      "339": "Enhanced Translation",
      "340": "Disaster Relief",
      "341": "Outreach",
      "342": "Census Income",
      "343": "Technical Changes",
      "344": "Other",
    },
    "61": {
      "431": "MAGI Eligiblity & Methods",
      "433": "XXI Medicaid Expansion",
      "435": "Eligibiity Process",
      "436": "Non-Financial Eligibility",
      "437": "Establish 2101(f) Group",
    },
    "64": { "419": "MAGI-CHIP" },
    "116": {
      "999": "Unwinding",
      "1000": "ARP 9821",
      "1001": "Evergreen",
      "1002": "COVID-19 PHE",
      "1003": "Other",
    },
  },
  "125": {
    "1": {
      "1": "ICF/MR Do Not Use",
      "2": "IH Do Not Use",
      "3": "IH_DSH Do Not Use",
      "4": "NF Do Not Use",
    },
    "2": {
      "5": "1931 Parents/Caretaker Do Not Use",
      "6": "ABI Do Not Use",
      "7": "Adult Foster Care Do Not Use",
      "8": "Aged-blind-disabled Do Not Use",
      "9": "Ambulatory Surgery Svcs Do Not Use",
      "10": "Bundled Payments Do Not Use",
      "11": "Case Management Do Not Use",
      "12": "Child Foster Care Do Not Use",
      "13": "Children non Foster Care Do Not Use",
      "14": "CHIP Authority exp Do Not Use",
      "15": "Chiropractor Do Not Use",
      "16": "Chron Disease Prev Incent Do Not Use",
      "156": "Clinic Do Not Use",
      "157": "Coverage Services SPA Do Not Use",
      "158": "Cvg Freestg Brth Ctrs Do Not Use",
      "159": "Dental Do Not Use",
      "160": "Disease Mangement Do Not Use",
      "161": "DSH Allotments Do Not Use",
      "162": "DSH Reduction Methodology Do Not Use",
      "163": "EPSDT Do Not Use",
      "164": "EPSDT non SBS Do Not Use",
      "165": "Family Planning Do Not Use",
      "166": "FQHC/RHC Do Not Use",
      "167": "Health Care Reform Do Not Use",
      "168": "HH Do Not Use",
      "169": "Hlth Homes Chronic Cond Do Not Use",
      "170": "Hospice for Children Do Not Use",
      "171": "LeadPaint Inspec/Remed Do Not Use",
      "172": "Maternity Do Not Use",
      "173": "Medical Day Care Do Not Use",
      "174": "Medically Fragile Adult Do Not Use",
      "175": "Medically Fragile Child Do Not Use",
      "176": "Mental Health Do Not Use",
      "177": "Mentally Ill Do Not Use",
      "178": "Newborn/New Mothers Do Not Use",
      "179": "Nurse Anesthetist Do Not Use",
      "180": "Nutritionist Do Not Use",
      "181": "Occupational Therapy Do Not Use",
      "182": "OP Do Not Use",
      "183": "OP Hospital Do Not Use",
      "184": "Optometrist Do Not Use",
      "185": "Other Do Not Use",
      "186": "PACE Do Not Use",
      "187": "PC Do Not Use",
      "188": "PDN Do Not Use",
      "189": "Personal Care Assistants Do Not Use",
      "190": "Persons with MR or DD Do Not Use",
      "191": "PHYS Do Not Use",
      "192": "Physical Therapy Do Not Use",
      "193": "Podiatrist Do Not Use",
      "194": "Preg Wom Tobbacco Cess 21 Do Not Use",
      "195": "Pregnant Women Do Not Use",
      "196": "Primary Care Services Pmt Do Not Use",
      "197": "Rehab Do Not Use",
      "198": "Rehab Svcs non SBS Do Not Use",
      "199": "Reimbursement Method Do Not Use",
      "200": "SBS EPSDT/Rehab Prov Do Not Use",
      "201": "School Based Servcs (SBS) Do Not Use",
      "202": "SPA Companion Lttr NIPT Do Not Use",
      "203": "Speech Therapy Do Not Use",
      "204": "Substance Abuse Do Not Use",
      "205": "TBI Do Not Use",
      "206": "TCM Do Not Use",
      "207": "TRAN Do Not Use",
      "208": "Transportation Do Not Use",
      "209": "Tuberculosis Do Not Use",
      "346": "Rate Modification Do Not Use",
      "347": "Physician Administered Drugs Do Not Use",
      "348": "Telemedicine Do Not Use",
      "359": "Licensed Providers Do Not Use",
      "364": "Preventable Conditions Do Not Use",
      "368": "ESRD Do Not Use",
      "374": "CMHCs Do Not Use",
      "376": "Chld Behavioral Svcs Do Not Use",
      "380": "Supplemental Payments Do Not Use",
      "388": "Integrated Care Model Do Not Use",
      "400": "Medicaid Trtment Chld Care  Do Not Use",
      "406": "Home Health Services Do Not Use",
      "408": "Eyeglasses Do Not Use",
      "409": "Hospice Do Not Use",
      "420": "Pediatric Vaccine Admin Do Not Use",
      "421": "Pschologist Services Do Not Use",
      "422": "Benchmark Do Not Use",
      "423": "Freestanding Birth Centers Do Not Use",
      "424": "Fee Schedule Do Not Use",
      "425": "Patient Centered Medical Home Do Not Use",
      "448": "Episodes of Care Do Not Use",
      "450": "Preventive Do Not Use",
    },
    "3": {
      "17": "Co-Pay Do Not Use",
      "18": "Dispensing Fees Do Not Use",
      "19": "Ingredient Cost Do Not Use",
      "20": "Ingredient Payment Do Not Use",
      "225": "Mail Order Payment Do Not Use",
      "226": "Specialty Drug Payment Do Not Use",
      "227": "State Max Allowance Cost Do Not Use",
      "228": "Supplemental Agreement Do Not Use",
      "286": "Vaccinations Do Not Use",
      "345": "Ingredient Pmt/Dispensing Fees Do Not Use",
    },
    "6": {
      "36": "Comparability Do Not Use",
      "37": "Cost Neutrality Do Not Use",
      "38": "Eligibility Restrictions Do Not Use",
      "39": "ICPs Do Not Use",
      "40": "Individual Evaluations Do Not Use",
      "41": "Level of Care Requirement Do Not Use",
      "42": "PT Do Not Use",
      "43": "Required Services Do Not Use",
      "44": "Self-Direction Do Not Use",
      "45": "State wideness Do Not Use",
      "356": "Establish HCB Service Do Not Use",
    },
    "7": {
      "46": "Self-Direction Do Not Use",
      "47": "SPA Option Do Not Use",
    },
    "8": { "48": "Community First Choice Do Not Use" },
    "9": { "49": "Other Do Not Use", "396": "SSI Children Do Not Use" },
    "10": {
      "50": "FEHPB Do Not Use",
      "51": "HMO Plan Coverage Do Not Use",
      "52": "Secretarial Coverage Do Not Use",
      "53": "State Employee Coverage Do Not Use",
      "392": "MMCP Do Not Use",
    },
    "11": { "54": "Other Do Not Use" },
    "12": {
      "55": "APD Do Not Use",
      "56": "APDU Do Not Use",
      "57": "IAPD Do Not Use",
      "58": "Managed Care Do Not Use",
      "59": "PAPD Do Not Use",
      "60": "PIHP Do Not Use",
      "61": "Other Do Not Use",
    },
    "13": {
      "62": "Amb Srvcs-Pregnant Women Do Not Use",
      "63": "Case Management Do Not Use",
      "64": "Clinics Do Not Use",
      "65": "Dental Do Not Use",
      "66": "Drugs & Related Services Do Not Use",
      "67": "Ext Svcs-Pregnant Women Do Not Use",
      "68": "Hospice Do Not Use",
      "69": "Medical & Surgical Do Not Use",
      "70": "not IMD Inpatient Hosp Do Not Use",
      "71": "Nurse Midwife Do Not Use",
      "72": "Other Licensed Pract Do Not Use",
      "73": "Pediatric NP & Cert NP Do Not Use",
      "74": "Personal Care Do Not Use",
      "75": "Private Duty Nursing Do Not Use",
      "76": "Respitory Care Do Not Use",
      "77": "Sickle Cell Treatment Do Not Use",
      "78": "TB Related Services Do Not Use",
      "271": "Freestanding Birth Centers Do Not Use",
      "349": "Rehab Do Not Use",
      "350": "Dental Do Not Use",
      "351": "Denture Do Not Use",
      "352": "Eyeglasses Do Not Use",
      "353": "Prosthetics Do Not Use",
      "354": "Preventative Services Do Not Use",
      "372": "lab and x-ray svcs Do Not Use",
      "378": "Physician Services Do Not Use",
      "383": "Tobacco Cessation Do Not Use",
      "393": "Multiple services Do Not Use",
      "402": "Transportation Do Not Use",
      "403": "Behavioral Services Do Not Use",
      "407": "PASRR Do Not Use",
      "413": "Nursing Home Stays Do Not Use",
      "426": "Alternative Benefit Plan Do Not Use",
      "442": "Home Health Do Not Use",
      "449": "TCM-Targeted Case Management  Do Not Use",
      "451": "Managed Care Do Not Use",
    },
    "14": {
      "79": "Diabetes Do Not Use",
      "80": "Smoke Cessation Do Not Use",
      "81": "Weight Management Do Not Use",
    },
    "15": {
      "82": "Prohibition of Payment Do Not Use",
      "83": "Provider Enrollment Do Not Use",
    },
    "16": {
      "84": "Adoptions Do Not Use",
      "85": "Aged Do Not Use",
      "86": "Annual Adjustment Do Not Use",
      "87": "Annuities Do Not Use",
      "88": "Asset Verification System Do Not Use",
      "89": "Blind Disabled Do Not Use",
      "90": "Breast & Cervical Cancer Do Not Use",
      "91": "Burial Funds Do Not Use",
      "92": "Children Do Not Use",
      "93": "Condition of Enrollment Do Not Use",
      "94": "Cost Sharing/Copayment Do Not Use",
      "95": "Coverage Non-Citizens Do Not Use",
      "96": "Crossover Claims Do Not Use",
      "97": "Deeming Do Not Use",
      "98": "Disregards Do Not Use",
      "99": "Dual Eligibles Do Not Use",
      "100": "ER Non-Emergent Condition Do Not Use",
      "101": "Estate Recovery Do Not Use",
      "102": "Express Lane Do Not Use",
      "103": "Family Opportunity Act Do Not Use",
      "104": "FPL Do Not Use",
      "105": "Inmates Do Not Use",
      "106": "Liens Do Not Use",
      "107": "Long Term Care Do Not Use",
      "108": "Medically Needy Do Not Use",
      "109": "MSP (Duals) Do Not Use",
      "110": "PACE Do Not Use",
      "111": "PARIS Do Not Use",
      "112": "PERM Do Not Use",
      "113": "Post Eligibility Do Not Use",
      "114": "Poverty Guidelines Do Not Use",
      "115": "Pregnant Women Do Not Use",
      "116": "Presumptive Eligibility Do Not Use",
      "117": "Provider Appeals Do Not Use",
      "118": "Single State Agency Do Not Use",
      "119": "Spenddown Do Not Use",
      "120": "Spousal Impoverishment Do Not Use",
      "121": "Substantial Home Equity Do Not Use",
      "122": "TMA Do Not Use",
      "123": "Transfer of Assets Do Not Use",
      "124": "Trusts Do Not Use",
      "125": "Veteran's Affairs Do Not Use",
      "126": "Working Disabled Do Not Use",
      "370": "Coverage Services Do Not Use",
      "371": "Family Planning Do Not Use",
      "390": "Supplemental payment Do Not Use",
      "391": "Home equity Do Not Use",
      "398": "Federal Benefit Rate Do Not Use",
      "438": "Income Standards Do Not Use",
      "439": "Fair Hearings and Appeals Do Not Use",
      "441": "Pregnant Minors Do Not Use",
      "444": "ABP Do Not Use",
      "453": "DOMA Do Not Use",
    },
    "17": { "127": "LeadPaint Inspec/Remed Do Not Use" },
    "18": {
      "128": "Background Checks Do Not Use",
      "129": "Chron Disease Prev Incent Do Not Use",
      "130": "Cvg Freestg Brth Ctrs Do Not Use",
      "131": "DSH Allotments Do Not Use",
      "132": "DSH Reduction Methodology Do Not Use",
      "133": "Early Election Mandty Grp Do Not Use",
      "134": "Elig Exp Mandty Grp Do Not Use",
      "135": "Family Planning Ctrs Do Not Use",
      "136": "Hlth Homes Chronic Cond Do Not Use",
      "137": "Hosp Acq Cond Pmt adj Do Not Use",
      "138": "Hospice for Children Do Not Use",
      "139": "Nonelderly Elig MGI Do Not Use",
      "140": "Preg Wom Tobbacco Cess 21 Do Not Use",
      "141": "Primary Care Services Pmt Do Not Use",
      "142": "State Incentives Do Not Use",
    },
    "19": { "145": "Other Do Not Use" },
    "20": {
      "146": "DSH Do Not Use",
      "147": "Hospital DSH Do Not Use",
      "148": "Hospital Inpatient Do Not Use",
      "149": "Hospital non DSH Do Not Use",
      "150": "ICF/MR Do Not Use",
      "151": "Nursing Facility Do Not Use",
      "152": "Preventive Conditions Do Not Use",
      "153": "Psych Res Treat Facility Do Not Use",
      "154": "UPL Demonstrations Do Not Use",
      "155": "Other Do Not Use",
      "377": "Hospital Acquired Conditions Do Not Use",
      "385": "Outpatient Hospital Do Not Use",
      "399": "Behavioral Health Providers Do Not Use",
      "401": "Provider Tax Do Not Use",
      "412": "DRG Methodology Do Not Use",
    },
    "21": { "394": "Former wards submission Do Not Use" },
    "22": {
      "210": "Active Pharm Ingredients Do Not Use",
      "211": "E-Prescribing Do Not Use",
      "212": "Excluded Drug Coverage Do Not Use",
      "213": "Lock-In Program Do Not Use",
      "214": "Mail Order Coverage Do Not Use",
      "215": "Max Branded Drug Limit Do Not Use",
      "216": "Max Generic Drug Limit Do Not Use",
      "217": "Max Prescription Limit Do Not Use",
      "218": "Maximum Quantity Limit Do Not Use",
      "219": "Maximum Refill Limitation Do Not Use",
      "220": "Multi-State SRA Do Not Use",
      "221": "Prior Authorization Do Not Use",
      "222": "Single- State SRA Do Not Use",
      "223": "Specialty Drug Coverage Do Not Use",
      "224": "Step Therapy Do Not Use",
      "285": "Vaccinations Do Not Use",
      "363": "Preferred Drug List Do Not Use",
      "367": "Dispensing Fee Do Not Use",
      "369": "Program Adherence Do Not Use",
      "382": "Payment Policy Do Not Use",
      "386": "Reduces Benefits/Cov Do Not Use",
      "389": "Dually Eligible Do Not Use",
      "410": "MIPPA of 2008 Do Not Use",
    },
    "23": { "229": "Other Do Not Use" },
    "24": {
      "230": "Audiology Do Not Use",
      "231": "Developmental Disability Do Not Use",
      "232": "Habilitation (OBRA'89) Do Not Use",
      "233": "MR-Related Conditions Do Not Use",
      "235": "Substance abuse Do Not Use",
    },
    "25": {
      "236": "Occupational Therapy Do Not Use",
      "237": "Personal Care Assistants Do Not Use",
      "238": "Physical Therapy Do Not Use",
      "239": "Speech Therapy Do Not Use",
      "240": "Transportation Do Not Use",
      "241": "Other Do Not Use",
      "288": "Transportation and EPSDT Do Not Use",
    },
    "26": { "242": "Other Do Not Use" },
    "27": { "243": "Other Do Not Use" },
    "28": {
      "244": "1931 Parents/Caretaker Do Not Use",
      "245": "ABI Do Not Use",
      "246": "Adult Foster Care Do Not Use",
      "247": "Aged-blind-disabled Do Not Use",
      "248": "Child Foster Care Do Not Use",
      "249": "Children non Foster Care Do Not Use",
      "250": "CHIP Authority exp Do Not Use",
      "251": "Coverage Services SPA Do Not Use",
      "252": "Maternity Do Not Use",
      "253": "Medically Fragile Adult Do Not Use",
      "254": "Medically Fragile Child Do Not Use",
      "255": "Mentally Ill Do Not Use",
      "256": "Newborn/New Mothers Do Not Use",
      "257": "Persons with MR or DD Do Not Use",
      "258": "Pregnant Women Do Not Use",
      "259": "Reimbursement Method Do Not Use",
      "260": "TBI Do Not Use",
      "261": "Tuberculosis Do Not Use",
    },
    "29": {
      "262": "Cost Sharing Do Not Use",
      "263": "Estate Recovery Do Not Use",
      "264": "Liens Do Not Use",
      "272": "COB/TPL Do Not Use",
    },
    "30": { "266": "Other Do Not Use" },
    "38": {
      "283": "Premiums/Enrollment Fees Do Not Use",
      "284": "Copays/Deductibles/Coinsurance Do Not Use",
    },
    "50": {
      "355": "Authority Change Do Not Use",
      "365": "Remove Svc Category Do Not Use",
      "366": "Remove Obsolete Pgs Do Not Use",
      "379": "Provider Appeal Timeframe Do Not Use",
      "387": "State Review Designation Do Not Use",
      "404": "Table of Contents Update Do Not Use",
      "443": "Electronic Claims  Do Not Use",
    },
    "51": { "357": "Administrative Do Not Use" },
    "52": { "360": "Updated Language Do Not Use" },
    "53": { "361": "Reimbursement Do Not Use" },
    "54": { "362": "Pharmacy Svcs Do Not Use" },
    "55": { "373": "Other Do Not Use" },
    "56": { "381": "Reimbursement Do Not Use", "397": "HCBS Do Not Use" },
    "57": { "384": "Grp Health Plans Do Not Use" },
    "58": { "395": "Crossover Claims Do Not Use" },
    "59": { "405": "Inpatient Facility  Do Not Use" },
    "60": {
      "414": "MAGI-Based Elig Groups Do Not Use",
      "415": "Eligibility Process Do Not Use",
      "416": "MAGI Income Methodology Do Not Use",
      "427": "Residency Do Not Use",
      "428": "Single State Agency Do Not Use",
      "429": "Citizenship & Immigration  Do Not Use",
      "430": "Hospital Presumptive Elig Do Not Use",
    },
    "62": {
      "417": "MAGI-Medicaid Do Not Use",
      "418": "Alternative Benefit Plan Do Not Use",
    },
    "67": { "440": "FMAP Claims - Adult Group Do Not Use" },
    "82": { "524": "RAC", "861": "ARP 9817", "888": "PHE Related" },
    "83": {
      "525": "COVID",
      "526": "Flood",
      "527": "Hurricane",
      "528": "Other Pandemic",
      "529": "Tropical Storms",
      "530": "Viral Outbreak",
      "531": "Wild Fire",
      "532": "Other",
      "862": "ARP 9817",
      "889": "PHE Related",
    },
    "84": {
      "533": "Authority Change",
      "534": "Electronic Claims",
      "535": "Fair Hearings and Appeals",
      "536": "Policy Update",
      "537": "Provider Appeal Timeframe",
      "538": "Provider sanctions",
      "539": "Remove Obsolete Pages",
      "540": "Remove Svc Category",
      "541": "Single State Agency",
      "542": "State Review Designation",
      "543": "Table of Contents Update",
      "544": "Utilization review Administration",
      "863": "ARP 9817",
      "890": "PHE Related",
    },
    "85": { "545": "Policy", "864": "ARP 9817", "891": "PHE Related" },
    "86": {
      "546": "1931 Parents/Caretaker",
      "547": "ABI",
      "548": "Adult Foster Care",
      "549": "Aged-blind-disabled",
      "550": "Ambulatory Surgery Svcs",
      "551": "Benchmark",
      "552": "Bundled Payments",
      "553": "Case Management",
      "554": "Child Behavioral Services",
      "555": "Child Foster Care",
      "556": "Children non Foster Care",
      "557": "CHIP Authority exp",
      "558": "Chiropractor",
      "559": "Chron Disease Prev Incent",
      "560": "Clinic",
      "561": "Community Mental Health Centers",
      "562": "Coverage Services SPA",
      "563": "Dental",
      "564": "Disease Management",
      "565": "Disproportionate Share Hospital",
      "566": "DSH Reduction Methodology",
      "568": "End Stage Renal Disease",
      "569": "Episodes of Care",
      "570": "EPSDT non School Based Services",
      "571": "Eyeglasses",
      "572": "Family Planning",
      "573": "Federally Qualified Health Centers",
      "574": "Federally Qualified Health Centers/ Rural Health Centers",
      "575": "Fee Schedule",
      "576": "Freestanding Birth Centers",
      "577": "Health Care Reform",
      "578": "Health Homes",
      "579": "Health Homes Chronic Cond",
      "580": "Home Health Services",
      "581": "Hospice",
      "582": "Hospice for Children",
      "583": "IHS Encounter Payment",
      "584": "Integrated Care Model",
      "585": "Lead Paint Inspec/Remed",
      "586": "Licensed Providers",
      "587": "Maternity",
      "588": "Medicaid Treatment Child Care",
      "589": "Medical Day Care",
      "590": "Medically Fragile Adult",
      "591": "Medically Fragile Child",
      "592": "Mental Health",
      "593": "Mentally Ill",
      "594": "Newborn/New Mothers",
      "595": "Nurse Anesthetist",
      "596": "Nutritionist",
      "597": "Occupational Therapy",
      "598": "OP",
      "599": "OP Hospital",
      "600": "Optometrist",
      "601": "Other",
      "602": "Patient Centered Medical Home",
      "603": "Pediatric Vaccine Admin",
      "604": "Personal Care",
      "605": "Personal Care Assistants",
      "606": "Persons with MR or DD",
      "607": "Physical Therapy",
      "608": "Physician",
      "609": "Physician Administered Drugs",
      "610": "Physician Services",
      "611": "Podiatrist",
      "612": "Preg Wom Tobbacco Cess 21",
      "613": "Pregnant Women",
      "614": "Preventable Conditions",
      "615": "Preventive",
      "616": "Primary Care Services Pmt",
      "617": "Private Duty Nursing",
      "618": "Program of All-Inclusive Care for the Elderly",
      "619": "Psychologist Services",
      "620": "Rate Modification",
      "621": "Rehab Services non School Based Service",
      "622": "Rehabilitative",
      "623": "Reimbursement Method",
      "624": "SBS EPSDT/Rehab Prov",
      "625": "School Based Services (SBS)",
      "626": "SPA Companion Letter NIPT",
      "627": "Speech Therapy",
      "628": "Substance Abuse",
      "629": "Supplemental Payments",
      "630": "Targeted Case Management",
      "631": "Telemedicine",
      "632": "TRAN",
      "633": "Transportation ",
      "634": "Traumatic Brain Injury",
      "635": "Tuberculosis",
      "865": "ARP 9817",
      "892": "PHE Related",
    },
    "87": {
      "636": "Behavioral Health Providers",
      "637": "Diagnosis Related Group Methodology",
      "638": "Disproportionate Share Hospital",
      "639": "Hospital Acquired Conditions",
      "640": "Hospital DSH",
      "641": "Hospital Inpatient",
      "642": "Hospital non DSH",
      "643":
        "Intermediate Care Facility for Individuals with Intellectual Disabilities",
      "644": "Nursing Facility",
      "645": "Nursing facility-PASRR",
      "646": "Other",
      "647": "Outpatient Hospital",
      "648": "Preventive Conditions",
      "649": "Provider Tax",
      "650": "Psych Res Treat Facility",
      "651": "Upper Payment Limit Demonstrations",
      "866": "ARP 9817",
      "893": "PHE Related",
    },
    "88": {
      "652": "Federal Medical Assistance Percentage",
      "867": "ARP 9817",
      "894": "PHE Related",
    },
    "89": {
      "653": "Upper Payment Limits",
      "868": "ARP 9817",
      "895": "PHE Related",
    },
    "90": {
      "654": "Administration",
      "869": "ARP 9817",
      "896": "PHE Related",
    },
    "91": {
      "655": "Alternative Benefit Plan",
      "656": "Amb Srvcs-Pregnant Women",
      "657": "Behavioral Services",
      "658": "Case Management",
      "659": "Chiropractic Services",
      "660": "Clinic Services",
      "661": "Dental",
      "662": "Denture",
      "663": "Disease Management",
      "664": "Drugs & Related Services",
      "665": "Emergency Services for Aliens",
      "666": "EPSDT",
      "667": "Ext Svcs-Pregnant Women",
      "668": "Eyeglasses ",
      "669": "Family Planning",
      "670": "Federally Qualified Health Centers",
      "671": "Freestanding Birth Centers",
      "672": "Home Health",
      "673": "Hospice",
      "674": "Inpatient Hospital",
      "675": "Integrated Care Model",
      "676": "Lab and X-ray Services",
      "677": "Lactation Consultation",
      "678": "Managed Care",
      "679": "Mandatory MAT Services (1006b)",
      "680": "Medical & Surgical",
      "681": "Multiple Services",
      "682": "not IMD Inpatient Hosp",
      "683": "Certified Nurse Midwife",
      "684": "Certified Pediatric/Family Nurse Practitioner",
      "685": "Nursing Home Stays",
      "686": "Optometrist Services",
      "687": "Organ Transplant",
      "688": "Other Licensed Practitioners",
      "689": "Outpatient Hospital",
      "690": "Personal Care Services",
      "691": "Physician Services",
      "692": "Podiatrist Services",
      "693": "Preventative Services",
      "694": "Primary Care Case Management",
      "695": "Private Duty Nursing",
      "696": "Prosthetics",
      "697": "Rehab Services",
      "698": "Respiratory Care",
      "699": "Rural Health Clinics",
      "700": "School Based Services",
      "701": "Screening",
      "702": "Sickle Cell Treatment",
      "703": "TB Related Services",
      "704": "TCM-Targeted Case Management",
      "705": "Telemedicine",
      "706": "Therapies – PT/OT/Speech & Hearing",
      "707": "Tobacco Cessation",
      "708": "Transportation",
      "870": "ARP 9817",
      "897": "PHE Related",
    },
    "92": {
      "709": "Inpatient Hospital",
      "710":
        "Inpatient Hospital –  Disproportionate Share Hospital Institutes for Mental Disease Services for People Over Age 65",
      "711":
        "Intermediate Care Facility for Individuals with Intellectual Disabilities",
      "712": "Nursing Facility",
      "713": "Preadmission Screening and Resident Review",
      "714": "Psychiatric Residential Treatment Facility",
      "715":
        "Psychiatric Residential Treatment Facility for Individuals Under Age 21",
      "871": "ARP 9817",
      "898": "PHE Related",
    },
    "93": {
      "716": "Amendment",
      "717": "Establish a new 1915(i) Benefit",
      "718": "Renewal",
      "853": "ARP 9817",
      "899": "PHE Related",
      "964": "Concurrent 1915(b)",
      "965": "Concurrent 1915(k)",
      "966": "Concurrent 1932(a)",
      "967": "Concurrent 1115",
      "968": "Concurrent 1915(j)",
    },
    "94": {
      "719": "Self-Direction",
      "720": "SPA Option",
      "855": "ARP 9817",
      "900": "PHE Related",
      "969": "Concurrent 1915(b)",
      "970": "Concurrent 1932(a)",
      "971": "Concurrent 1115",
      "972": "Concurrent 1915(c)",
      "973": "Concurrent 1915(i)",
      "974": "Concurrent 1915(k)",
    },
    "95": {
      "721": "Community First Choice",
      "857": "ARP 9817",
      "901": "PHE Related",
      "975": "Concurrent 1915(b)",
      "976": "Concurrent 1932(a)",
      "977": "Concurrent 1115",
      "978": "Concurrent 1915(i)",
      "979": "Concurrent 1915(j)",
    },
    "96": {
      "722": "Support Act IMD Coverage",
      "859": "ARP 9817",
      "902": "PHE Related",
    },
    "97": {
      "723": "ABP1:  Alternative Benefit Plan Populations",
      "724":
        "ABP2a: Voluntary Benefit Package Selection Assurances - Eligibility Group under Section 1902(a)(10)(A)(i)(VIII) of the Act",
      "725":
        "ABP2b: Voluntary Enrollment Assurances for Eligibility Groups other than the Adult Group under Section 1902(a)(10)(A)(i)(VIII) of the Act",
      "726": "ABP2c: Enrollment Assurances - Mandatory Participants",
      "727":
        "ABP3:  Selection of Benchmark Benefit Package or Benchmark-Equivalent Benefit Package (Use only if ABP has an effective date earlier than 1/1/2020 or if only changing the Section 1937 Coverage Option of an ABP implemented before 1/1/2020)",
      "728":
        "ABP3.1:  Selection of Benchmark Benefit or Benchmark-Equivalent Benefit Package (Use only for ABP's effective on or after 1/1/2020)",
      "729": "ABP4:  Alternative Benefit Plan Cost-Sharing",
      "730": "ABP5:  Benefits Description",
      "731": "ABP6:  Benchmark-Equivalent Benefit Package",
      "732": "ABP7:  Benefits Assurances",
      "733": "ABP8:  Service Delivery Systems",
      "734": "ABP9:  Employer Sponsored Insurance and Payment of Premiums",
      "735": "ABP10: General Assurances",
      "736": "ABP11: Payment Methodology",
      "872": "ARP 9817",
      "903": "PHE Related",
    },
    "98": {
      "737": "Eligibility",
      "738": "Description of rate methodology",
      "873": "ARP 9817",
      "904": "PHE Related",
    },
    "99": {
      "739": "Regular",
      "740": "SUD focused",
      "741": "Medically Complex Children (available 10/2022)",
      "874": "ARP 9817",
      "905": "PHE Related",
    },
    "100": { "742": "Other", "875": "ARP 9817", "906": "PHE Related" },
    "101": {
      "743": "340B",
      "744": "Professional Dispensing Fees",
      "745": "Ingredient Payment",
      "746": "Ingredient Pmt/Professional Dispensing Fees",
      "747": "Mail Order Payment",
      "748": "Specialty Drug Payment",
      "749": "State Max Allowance Cost",
      "750": "Supplemental Agreement",
      "751": "Value/Outcomes Based Purchasing",
      "876": "ARP 9817",
      "907": "PHE Related",
    },
    "102": {
      "752": "Active Pharm Ingredients",
      "753": "Dually Eligible",
      "754": "E-Prescribing",
      "755": "Excluded Drug Coverage",
      "756": "Lock-In Program",
      "757": "Mail Order Coverage",
      "758": "Max Branded Drug Limit",
      "759": "Max Generic Drug Limit",
      "760": "Max Prescription Limit",
      "761": "Maximum Quantity Limit",
      "762": "Maximum Refill Limitation",
      "763": "Multi-State SRA",
      "764": "Payment Policy",
      "765": "Preferred Drug List",
      "766": "Prior Authorization",
      "767": "Program Adherence",
      "768": "Reduces Benefits/Cov",
      "769": "Single- State SRA",
      "770": "Specialty Drug Coverage",
      "877": "ARP 9817",
      "908": "PHE Related",
    },
    "103": {
      "771": "Program Adherence",
      "878": "ARP 9817",
      "909": "PHE Related",
    },
    "104": {
      "772": "Primary Care Case Management",
      "773": "Primary Care Case Management Entity",
      "774": "Managed Care Organization",
      "775": "Tribal Primary Care Case Management",
      "776": "Tribal Primary Care Case Management Entity",
      "777": "Tribal Managed Care Organization",
      "879": "ARP 9817",
      "910": "PHE Related",
      "959": "Concurrent 1915(c)",
      "960": "Concurrent 1915(i)",
      "961": "Concurrent 1915(j)",
      "962": "Concurrent 1915(k)",
      "963": "Concurrent 1115",
    },
    "105": {
      "778": "Coordination of Benefits & Third Party Liability",
      "779": "Estate Recovery",
      "780": "Liens",
      "781": "Medicare Cost Sharing",
      "885": "ARP 9817",
      "911": "PHE Related",
    },
    "106": {
      "782": "Copays/Deductibles/Coinsurance",
      "783": "Premiums/Enrollment Fees",
      "880": "ARP 9817",
      "912": "PHE Related",
    },
    "107": {
      "784": "Aged/Blind/Disabled Eligibility",
      "785": "Application",
      "786": "Asset Verification System",
      "787": "Authorized Representative",
      "788": "Breast & Cervical Cancer",
      "789": "Citizenship and Non-Citizen Eligibility",
      "790": "Cost of Living Adjustment",
      "791": "Cost Sharing/Copayment",
      "792": "Disabled Children",
      "793": "Disregards",
      "794": "Eligibility Process",
      "795": "Express Lane",
      "796": "Family Planning",
      "797": "Family/Adult Eligibility",
      "798": "Federal Benefit Rate",
      "799": "Home Equity",
      "800": "Hospital Presumptive Eligibility",
      "801": "Income Standard—Territories",
      "802": "Income/Resource Methodologies",
      "803": "Institutional Eligibility",
      "804": "Medically Needy",
      "805": "Medicare Savings Programs (Duals)",
      "806": "Post Eligibility Treatment of Income",
      "807": "Pregnant Women",
      "808": "Presumptive Eligibility",
      "809": "Public Assistance Reporting Information System",
      "810": "Residency",
      "811": "Spenddown",
      "812": "Spousal Impoverishment",
      "813": "Transfer of Assets",
      "814": "Treatment of Trusts",
      "881": "ARP 9817",
      "886": "Extended Postpartum",
      "913": "PHE Related",
    },
    "108": {
      "815": "Cost Effectiveness",
      "816": "Other",
      "882": "ARP 9817",
      "914": "PHE Related",
    },
    "109": { "817": "Tribal", "883": "ARP 9817", "915": "PHE Related" },
    "110": {
      "818": "Provider Screening/Enrollment",
      "819": "Medicaid Eligibility Quality Control",
      "884": "ARP 9817",
      "916": "PHE Related",
    },
    "117": { "1005": "Reporting" },
  },
  "128": { "72": { "445": "PAPD", "446": "IAPD", "447": "APD-U" } },
  "129": {
    "79": {
      "492": "Tribal",
      "497": "SPMP",
      "502": "School Based",
      "507": "MMIS",
      "512": "Local Health Jurisdiction",
      "517": "Other",
    },
    "80": {
      "493": "Tribal",
      "498": "SPMP",
      "503": "School Based",
      "508": "MMIS",
      "513": "Local Health Jurisdiction",
      "518": "Other",
    },
    "81": {
      "494": "Tribal",
      "499": "SPMP",
      "504": "School Based",
      "509": "MMIS",
      "514": "Local Health Jurisdiction",
      "519": "Other",
    },
  },
  "130": {
    "77": {
      "456": "ICF/IID",
      "460": "Clinic",
      "464": "Nursing Facility",
      "468": "Psych Res Treat Facility",
      "472": "Hospital Inpatient",
      "476": "Hospital Outpatient",
      "480": "Physician/Practitioner",
      "484": "IMD",
      "488": "Other",
      "520": "DME",
      "522": "ClinicalDiagnosticLabServices",
    },
    "78": {
      "457": "ICF/IID",
      "461": "Clinic",
      "465": "Nursing Facility",
      "469": "Psych Res Treat Facility",
      "473": "Hospital Inpatient",
      "477": "Hospital Outpatient",
      "481": "Physician/Practitioner",
      "485": "IMD",
      "489": "Other",
      "521": "DME",
      "523": "ClinicalDiagnosticLabServices",
    },
  },
};
