service: ${self:custom.project}-backup

frameworkVersion: "3"

plugins:
  - serverless-stack-termination-protection
  - "@stratiformdigital/serverless-s3-security-helper"

provider:
  name: aws
  region: ${env:REGION_A}
  stackTags:
    PROJECT: ${self:custom.project}
    SERVICE: ${self:service}

custom:
  project: ${env:PROJECT}

resources:
  Resources:
    AttachmentsBackupBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${sls:stage}-attachments-backup-${aws:accountId}
    EventsBackupBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${sls:stage}-events-backup-${aws:accountId}
  Outputs:
    AttachmentsBackupBucketName:
      Value: !Ref AttachmentsBackupBucket
    AttachmentsBackupBucketArn:
      Value: !GetAtt AttachmentsBackupBucket.Arn
    EventsBackupBucketName:
      Value: !Ref EventsBackupBucket
    EventsBackupBucketArn:
      Value: !GetAtt EventsBackupBucket.Arn
