name: Accessibility Tests

on:
  push:
    branches:
      - "*"
      - "!skipci"
      - "!snyk"
      - "!snyk-*"
  schedule:
    - cron: "30 01 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref_name }}-accessibility
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JSON_ARTIFACT_ID: json-accessibility-report
      HTML_ARTIFACT_ID: html-accessibility-report
    steps:
      - name: Set report name
        id: variables
        run: |
          if [[ ${{ github.ref_name }} == 'main' ]]; then
            echo "report_name=main" >> "$GITHUB_OUTPUT"
          else
            echo "report_name=${{ github.run_id }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout
        uses: actions/checkout@v6
      - uses: ./.github/actions/setup

      - name: Install playwright dependencies
        working-directory: react-app
        run: bunx playwright install --with-deps chromium --force

      - name: Build UI
        working-directory: react-app
        run: bun run build

      - name: Run tests
        id: accessibility-test
        working-directory: react-app
        run: bun run test-storybook

      - name: Rename Reports
        if: ${{ !cancelled() }}
        run: |
          if [ -d "accessibility" ]; then
            cd accessibility
            mv json-report.json ${{ steps.variables.outputs.report_name }}.json
            mv html-report ${{ steps.variables.outputs.report_name }}
          fi

      - name: Upload JSON Report
        uses: actions/upload-artifact@v6
        id: upload-json
        if: ${{ !cancelled() }}
        with:
          name: ${{ env.JSON_ARTIFACT_ID }}
          path: accessibility/${{ steps.variables.outputs.report_name }}.json
          retention-days: 30

      - name: Upload HTML Report
        uses: actions/upload-artifact@v6
        id: upload-html
        if: ${{ !cancelled() }}
        with:
          name: ${{ env.HTML_ARTIFACT_ID }}
          path: accessibility/${{ steps.variables.outputs.report_name }}
          retention-days: 30
