name: Create Release PR - production

on:
  push:
    branches: val

jobs:
  pull-request:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: production
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: Release to production
          pr_body: |
            Release to production.

            #### Please **create a merge commit**
