name: Code Coverage Report

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 01 * * *"
  workflow_dispatch:

# ensures that currently running Code Coverage Report workflow is canceled if another job starts
concurrency:
  group: ${{ github.workflow }}-main
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  coverage-report:
    runs-on: ubuntu-latest
    env:
      JSON_ARTIFACT_ID: main-coverage
      HTML_ARTIFACT_ID: html-main-coverage-report
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: main
      - uses: ./.github/actions/setup
      - name: Test
        continue-on-error: true
        run: run test --coverage
      - name: Report coverage to Qlty
        if: always()
        uses: qltysh/qlty-action/coverage@v2
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage/lcov.info
      - name: Upload Coverage Summary
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        id: upload-json
        with:
          name: ${{ env.JSON_ARTIFACT_ID }}
          path: coverage/coverage-summary.json
          overwrite: true
          retention-days: 90
      - name: Upload Coverage Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        id: upload-html
        with:
          name: ${{ env.HTML_ARTIFACT_ID }}
          path: coverage/html-report/*
          overwrite: true
          retention-days: 90
