name: ESLint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - name: Install Dependencies
        run: run install

      - name: Run ESLint
        run: bun lint
