name: Security Group Cleanup

on:
  # schedule:
  #   - cron: "0 2 * * *"
  # workflow_dispatch:
  push:
    branches:
      - "dfix"

jobs:
  security-group-cleanup:
    name: Security Group Cleanup
    runs-on: ubuntu-20.04

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
          aws-region: us-east-1
          role-duration-seconds: 10800

      - name: Clean Up Unassigned Security Groups
        id: runningStages
        run: |
          sglist=(`aws ec2 describe-security-groups \
            --filters Name=tag:PROJECT,Values="om" \
            --query "SecurityGroups[?Attachments == null].GroupId" \
            --output text`)
          for i in "${sglist[@]}"
          do
            echo "Deleting $i..."
          done