name: Coverage Report

on:
  pull_request:
    branches:
      - main

jobs:
  coverage-report:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Test
        run: run test --coverage
      - name: Report Coverage
        if: always() 
        uses:  davelosert/vitest-coverage-report-action@v2